import type { ModulePack } from "@/lib/modules/types";

/**
 * Authority Relatable Mixer: WS09 role constraints (艺人/直播主/老师/博主).
 * Optional portfolio lens: fw.content-roles-3plus2.
 */
export const AUTHORITY_RELATABLE_MIXER_PACK: ModulePack = {
  moduleId: "authority-relatable-mixer",
  intakeFields: [
    {
      id: "role",
      label: "Primary role (艺人 / 直播主 / 老师 / 博主)",
      placeholder: "Pick the closest: 艺人, 直播主, 老师, or 博主",
      required: true,
    },
    {
      id: "usualShowUp",
      label: "How you usually show up",
      placeholder: "What you currently film or say on camera",
      required: true,
    },
    {
      id: "stiffOrCasual",
      label: "Where you feel stiff or too casual",
      placeholder: "Describe the mismatch",
      required: true,
      multiline: true,
    },
    {
      id: "audienceNeed",
      label: "What audience needs to trust you",
      placeholder: "Credibility, warmth, both…",
      required: true,
    },
    {
      id: "format",
      label: "Format",
      placeholder: "Reel, live, long video…",
      required: false,
    },
  ],
  probeHints: [
    "权威和共鸣",
    "艺人",
    "直播主",
    "老师",
    "博主",
    "内容角色",
    "3+2",
    "距离感",
    "信任感",
    "建议 vs 自我",
    "创始人出镜",
    "probe_jeff",
  ],
  boundNodeIds: [
    "src.workshop.ws-clips.batch1",
    "fw.content-roles-3plus2",
    "pr.advice-vs-ego",
    "pr.founder-face-printshop",
    "pr.standpoint-or-invisible",
    "pr.exposure-trust-conversion",
  ],
  starterPrompt:
    "Using my intake and WS09 role constraints (艺人/直播主/老师/博主), give a mix brief: what this role can show, what it must not overplay, and one filmable beat.",
  chatOpener:
    "I will mix authority and relatability using Jeff WS09 role constraints (艺人 / 直播主 / 老师 / 博主). Which role is closest to how you sell trust?",
  chatOpenerZh:
    "我会按 WS09 角色约束（艺人 / 直播主 / 老师 / 博主）帮你混搭权威与亲和。你最接近哪一种角色？",
  systemOverlay: [
    "## Module mode: Authority Relatable Mixer",
    "You are running the Authority Relatable Mixer tool for this user.",
    "Job: mix authority and relatability; name what the role can and should not overplay.",
    "",
    "### WS09 role constraints (hard; do not dodge)",
    "Source: workshop WS clips batch-1, WS09 权威和共鸣 (`src.workshop.ws-clips.batch1`).",
    "Different roles sell different things. Apply these constraints every time:",
    "- 艺人 → sells 距离感 (distance / aura). Relatable content that collapses distance can weaken the role.",
    "- 直播主 → sells 信任感 (felt trust / presence). Overplaying cold expert distance can weaken the role.",
    "- 老师 vs 博主 → content mix differs: teacher authority vs blogger traffic/relatability. Do not blur them into one generic \"creator\" voice.",
    "Authority roles constrain what \"relatable\" content you show. Name the user's primary role before advising the mix.",
    "Do not claim the KB is thin on roles while ignoring WS09. If a detail is missing, ask; do not invent a fake Jeff role-matrix brand name beyond these role terms and optional `fw.content-roles-3plus2`.",
    "",
    "### Optional portfolio lens",
    "When useful, map beats to content roles + 3+2 (`fw.content-roles-3plus2`): 权威型 / 流量型 / 信任型 / 关系型 / 故事共鸣型, and a 3+2 mix note. Do not force the full portfolio if the user only needs a single-role mix.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks over a generic business questionnaire.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "1. Role read: 艺人 / 直播主 / 老师 / 博主 (or honest hybrid with primary).",
    "2. What this role sells (距离感 vs 信任感 vs teacher vs blogger mix).",
    "3. Show more / dial down under that constraint.",
    "4. One filmable beat that balances authority with human without breaking the role.",
    "5. Ego trap note: relatability is not self-pity theater; authority is not flex.",
    "6. Optional: one 3+2 portfolio tip if it clarifies next posts.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume; value then convert where relevant.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Bind WS09 + optional fw.content-roles-3plus2. No overnight-fame. Never invent Jeff niche case studies.",
    "",
    "### Evidence binding",
    "Prefer: src.workshop.ws-clips.batch1, fw.content-roles-3plus2, pr.advice-vs-ego, pr.founder-face-printshop, pr.standpoint-or-invisible, pr.exposure-trust-conversion when in the pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the brief",
    "End with one direct question: which beat they will film this week.",
  ].join("\n"),
};
