import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * 评论回应三句法 (D1 p028). In-thread reply craft only.
 * Quality Runtime (Q4): reply-micro-convert family (short-but-complete; confirm light).
 */
export const COMMENT_REPLY_THREE_LINES_PACK: ModulePack = {
  moduleId: "comment-reply-three-lines",
  qualityRuntime: true,
  qualityFamily: "reply-micro-convert",
  confirmBlurb:
    "If needed, mirror in one short beat: comment caught, standpoint, and that you will draft 接住 → 澄清 → 拉回主轴 options. For short replies you may deliver when criticals are filled.",
  deliverableSectionOrder: [
    "2 to 3 reply drafts (接住 → 澄清 → 拉回主轴)",
    "Stop-drain / keep-publishing notes",
    "Teach / clarify / boundary tags",
    "Named refine levers",
  ],
  refineLevers: [
    "softer 接住",
    "clearer 澄清",
    "stronger 拉回主轴",
    "firmer boundary",
    "which reply to post",
  ],
  intakeFields: [
    {
      id: "comment",
      label: "Comment or pushback to answer",
      placeholder: "Paste the comment, DM, or pushback",
      required: true,
      multiline: true,
    },
    {
      id: "standpoint",
      label: "Your standpoint / facts",
      placeholder: "What you believe or know to be true here",
      required: true,
      multiline: true,
    },
    {
      id: "audience",
      label: "Who this content was for",
      placeholder: "The person the original post serves",
      required: true,
    },
    {
      id: "goal",
      label: "Reply goal",
      placeholder: "Teach, clarify, invite, or set a boundary",
      required: false,
    },
  ],
  qualitySlots: [
    {
      id: "comment",
      label: "Comment or pushback to answer",
      criticality: "critical",
      probeHint: "Paste the comment, DM, or pushback to answer.",
      placeholder: "Paste the comment, DM, or pushback",
      multiline: true,
      idkOptions: [
        "Paste a short skeptical comment about your tip (scaffold; they paste).",
        "Paste a price or timing pushback (scaffold; they paste).",
        "Paste a personal attack that still needs a calm reply (scaffold; they paste).",
        "Or paste the real comment in their own words.",
      ],
    },
    {
      id: "standpoint",
      label: "Your standpoint / facts",
      criticality: "critical",
      probeHint: "What you believe or know to be true here. Advice over ego.",
      placeholder: "What you believe or know to be true here",
      multiline: true,
      idkOptions: [
        "You teach systems, not overnight results (scaffold; they reword).",
        "Criticism is signal or noise; you keep publishing either way (scaffold; they reword).",
        "You answer for the ideal customer watching, not to win strangers (scaffold; they reword).",
        "Or say your standpoint in one plain sentence.",
      ],
    },
    {
      id: "audience",
      label: "Who this content was for",
      criticality: "critical",
      probeHint: "The person the original post serves (ideal customer, not the troll).",
      placeholder: "The person the original post serves",
      idkOptions: [
        "The buyer who is quietly reading the thread (scaffold; they name them).",
        "Warm followers who need judgment, not a fight (scaffold; they correct).",
        "A specific role your post was teaching (scaffold; they name the role).",
        "Or name who the content was for.",
      ],
    },
    {
      id: "goal",
      label: "Reply goal",
      criticality: "optional",
      probeHint: "Optional: teach, clarify, invite, or set a boundary.",
      placeholder: "Teach, clarify, invite, or set a boundary",
    },
  ],
  idkOptionsBySlotId: {
    comment: [
      "Paste a short skeptical comment about your tip (scaffold; they paste).",
      "Paste a price or timing pushback (scaffold; they paste).",
      "Paste a personal attack that still needs a calm reply (scaffold; they paste).",
      "Or paste the real comment in their own words.",
    ],
    standpoint: [
      "You teach systems, not overnight results (scaffold; they reword).",
      "Criticism is signal or noise; you keep publishing either way (scaffold; they reword).",
      "You answer for the ideal customer watching, not to win strangers (scaffold; they reword).",
      "Or say your standpoint in one plain sentence.",
    ],
    audience: [
      "The buyer who is quietly reading the thread (scaffold; they name them).",
      "Warm followers who need judgment, not a fight (scaffold; they correct).",
      "A specific role your post was teaching (scaffold; they name the role).",
      "Or name who the content was for.",
    ],
  },
  probeHints: [
    "评论回应三句法",
    "comment reply",
    "接住",
    "澄清",
    "拉回主轴",
    "advice vs ego",
    "standpoint",
    "批评",
    "立场",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.comment-reply-three-lines",
    "pr.advice-vs-ego",
    "pr.standpoint-or-invisible",
    "cl.criticism-not-failure",
  ],
  starterPrompt:
    "Using my intake, draft 评论回应三句法 replies: 接住, 澄清, 拉回主轴 (plus stop-drain / keep-publishing notes when needed).",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you draft a three-line comment reply.",
    firstAsk: "Paste the comment you want to answer.",
    seed: "comment-reply-three-lines",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你按三句法起草评论回复。",
    firstAsk: "把要回的评论丢给我。",
    seed: "comment-reply-three-lines",
  }),
  systemOverlay: [
    "## Module mode: 评论回应三句法 (qualityRuntime Reply/Micro-convert)",
    "You are running the 评论回应三句法 tool for this user.",
    "Name while applying: Jeff's <<评论回应三句法>> / Jeff 的 <<评论回应三句法>> (`fw.comment-reply-three-lines`). Apply; do not lecture.",
    "Job: draft in-thread replies. Not a Reel script.",
    "Framing: 回应不是为了赢网友，是为了让目标客户看见你的判断.",
    "Slide moves (title says 三句; body lists more): 接住, 澄清, 拉回主轴, 停止消耗, 继续发布.",
    "Do not invent a different formula name. Do not run B.R.E.A.K Shield here; that is a separate module.",
    "Lifecycle: Collect criticals, then short-but-complete Deliver. Confirm is light for this family (optional one-beat mirror). Refine after drafts exist.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Deliver: the comment, standpoint/facts, and who the original content was for.",
    "Ask at most 1 to 2 questions per Collect turn.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent niche facts.",
    "",
    "### Deliverable shape (short-but-complete)",
    "1. Two to three reply drafts using 接住 → 澄清 → 拉回主轴.",
    "2. Note when to 停止消耗 (stop draining) and how to 继续发布 (next content).",
    "3. Mark each draft: teach / clarify / boundary.",
    "4. End with named refine levers.",
    "Do not write a full content script here.",
    "",
    "### Refine",
    "After drafts exist, tweak named levers only. Do not re-ask filled critical slots.",
    "",
    "### Jeff distinctiveness (hard)",
    "Advice vs ego. Standpoint. Content assets not ads.",
    "ANTI-GENERIC: If this reply could have come from a generic social media coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Bind to fw.comment-reply-three-lines. No overnight-fame. Never invent Jeff niche case studies as doctrine.",
    "",
    "### Evidence binding",
    "Prefer: fw.comment-reply-three-lines, pr.advice-vs-ego, pr.standpoint-or-invisible, cl.criticism-not-failure when in the pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the drafts",
    "End with one direct question: which reply they will post.",
  ].join("\n"),
};
