import type { ModulePack } from "@/lib/modules/types";

/**
 * 九宫格 / Topic Bingo ideation (AUG-D2).
 * Module id kept as content-ideation-ip for stable routes.
 * Not The Waffle (fw.waffle-grid): that is a separate format×theme tool.
 */
export const CONTENT_IDEATION_IP_PACK: ModulePack = {
  moduleId: "content-ideation-ip",
  intakeFields: [
    {
      id: "renshe",
      label: "人设 (center)",
      placeholder: "Who you are on camera: role, face, what the market should remember",
      required: true,
      multiline: true,
    },
    {
      id: "interestPro",
      label: "兴趣 / 专业",
      placeholder: "Interest keywords and professional expertise keywords",
      required: true,
      multiline: true,
    },
    {
      id: "viewStory",
      label: "观点 / 故事",
      placeholder: "Standpoints you will own, and stories you can tell",
      required: true,
      multiline: true,
    },
    {
      id: "customerIndustry",
      label: "客户 / 行业",
      placeholder: "Who buys, and how your industry actually works",
      required: true,
      multiline: true,
    },
    {
      id: "trendPain",
      label: "趋势 / 痛点",
      placeholder: "Trends you can teach on, and pains customers already feel",
      required: true,
      multiline: true,
    },
  ],
  probeHints: [
    "穿心线",
    "人设",
    "兴趣",
    "专业",
    "观点",
    "故事",
    "客户",
    "行业",
    "趋势",
    "痛点",
    "九宫格",
    "topic bingo",
    "选题",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.jiugongge-topic-bingo",
    "fw.crossing-lines",
    "pr.direction-beats-volume",
    "cl.content-not-ads",
  ],
  starterPrompt:
    "Using my intake, fill AUG-D2 九宫格 / Topic Bingo: center 人设, eight cells 兴趣/专业/观点/故事/客户/行业/趋势/痛点, then 四条穿心线 into about 12 topic seeds.",
  chatOpener:
    "I will run 九宫格 / Topic Bingo the AUG-D2 way: center 人设, eight cells, then 四条穿心线 into about 12 topic seeds. In plain words, what is your 人设: who should the market remember you as?",
  chatOpenerZh:
    "我会按 AUG-D2 九宫格 / Topic Bingo 来：中心是人设，八格是兴趣/专业/观点/故事/客户/行业/趋势/痛点，再画四条穿心线长出大约 12 个题目雏形。先用白话说你的人设：市场该把你记成谁？",
  systemOverlay: [
    "## Module mode: 九宫格 Topic Bingo (AUG-D2)",
    "You are running the 九宫格 / Topic Bingo tool (catalog id content-ideation-ip) for this user.",
    "Job: Fill Jeff Day-2 Topic Bingo, then draw 四条穿心线 into about 12 topic seeds. Not random volume ideation. Not The Waffle multiplication plan.",
    "",
    "### Jeff grid structure (hard; use these exact cell labels)",
    "1. Center cell: 人设",
    "2. Eight surrounding cells, exact Jeff names only: 兴趣 / 专业 / 观点 / 故事 / 客户 / 行业 / 趋势 / 痛点",
    "3. Draw 四条穿心线 (four crossing lines through the grid). Each line = one content direction (demo pattern: 专业×痛点).",
    "4. Each line → at least 3 topic seeds. Target: one filled 九宫格 + about 12 题目雏形.",
    "Bosses should not rely on daily inspiration; sit once and fill the grid.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks: start with 人设, then fill the eight cells with keywords from their real work.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "1. 九宫格: center 人设 + eight cells labeled exactly 兴趣/专业/观点/故事/客户/行业/趋势/痛点, each with short keywords from THEIR facts.",
    "2. 四条穿心线: name each line as cell×cell (or cell through 人设), one sentence direction each.",
    "3. Topic seeds: about 12 题目雏形 (3+ per line). Filmable titles, grounded in their answers.",
    "4. Optional one-line note that this can later expand toward a 30-day bank; do not invent a full calendar unless asked.",
    "",
    "### Hard bans",
    "Do NOT invent a process / FAQ / result / standpoint grid. That is not this tool.",
    "Do NOT tag cells or topics with see / trust / convert (or 被看见/信任/转化) as the grid taxonomy.",
    "Do NOT run The Waffle format×theme ~100-video plan here. Prefer fw.jiugongge-topic-bingo + fw.crossing-lines only.",
    "Do NOT invent English cell names that replace the Jeff Chinese labels.",
    "No overnight-fame. No inventing Jeff niche case studies.",
    "",
    "### Jeff distinctiveness (hard)",
    "Direction beats volume. Content assets not ads. Ground every cell and every 穿心线 in their words.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff 九宫格, rewrite before sending.",
    "",
    "### Evidence binding",
    "Prefer: fw.jiugongge-topic-bingo, fw.crossing-lines, pr.direction-beats-volume, cl.content-not-ads when in the pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the grid",
    "End with one direct question: which 穿心线 (or which of the 12 seeds) they will script this week.",
  ].join("\n"),
};
