import type { ModulePack } from "@/lib/modules/types";

/**
 * Content Not Working Checklists: stakeholder Framework Needed PDF tool.
 * Elevated draft doctrine; not approved.
 */
export const CONTENT_NOT_WORKING_CHECKLISTS_PACK: ModulePack = {
  moduleId: "content-not-working-checklists",
  intakeFields: [
    {
      id: "symptom",
      label: "Symptom",
      placeholder: "Nobody watching, or no ideas to film, or both",
      required: true,
    },
    {
      id: "whatSold",
      label: "The business: what is actually sold",
      placeholder: "Offer in plain words",
      required: true,
    },
    {
      id: "methodGuess",
      label: "The method: loud or quiet",
      placeholder: "Outgoing vs reserved; which route they were handed",
      required: true,
    },
    {
      id: "customerWords",
      label: "The words customers use",
      placeholder: "How buyers actually talk about the problem",
      required: true,
      multiline: true,
    },
    {
      id: "positioningGuess",
      label: "Positioning guess",
      placeholder: "Who it is for, in one sentence",
      required: true,
      multiline: true,
    },
  ],
  probeHints: [
    "没人看",
    "没得拍",
    "定位",
    "诊断清单",
    "nobody is watching",
    "no ideas to film",
    "content checklist",
    "positioning problem",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.content-not-working-checklists",
    "fw.two-kinds-student-two-methods",
    "fw.waffle-grid",
    "fw.jiugongge-topic-bingo",
    "fw.positioning-four-questions",
  ],
  starterPrompt:
    "Using my intake, run Content Not Working Checklists A and/or B in exact Jeff order, cite my facts at each gate, and name next tools when ideas are empty.",
  chatOpener:
    "I will run the Content Not Working checklists. Positioning before camera tricks. Is the main symptom nobody watching, no ideas to film, or both?",
  chatOpenerZh:
    "我会跑「内容失效」两套教练清单。先定位，再谈拍摄技巧。主症状是没人看、没得拍，还是两个都有？",
  systemOverlay: [
    "## Module mode: Content Not Working Checklists",
    "You are running the Content Not Working Checklists tool (catalog id content-not-working-checklists) for this user.",
    "Job: Run the two coach checklists. Most problems that look like filming problems are positioning problems.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks over a generic business questionnaire.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Checklist A: Nobody is watching (exact order; hard)",
    "Walk gates in this order only. At each gate, cite a user fact (quote or paraphrase). Do not skip ahead.",
    "1. The business: what is actually sold",
    "2. The method: loud route or quiet route",
    "3. The words: do customers talk like this",
    "4. Positioning: usually the real answer",
    "",
    "### Checklist B: No ideas to film (exact order; hard)",
    "1. Fix the positioning first",
    "2. Decide loud type or quiet type",
    "3. Fill in the grid and their themes",
    "4. Use the AI assistant to draft from it",
    "When naming next tools after B: Two Kinds of Student (loud/quiet), then The Waffle or 九宫格 / Topic Bingo for the grid. Do not invent a third grid name.",
    "PDF note: a student who has done all four has more work queued than they can film in a quarter.",
    "",
    "### Output format (when ready to generate)",
    "1. Pick checklist A and/or B from the symptom.",
    "2. Walk the chosen checklist(s) in exact order above. Pass/fail or unclear each gate with a user-fact cite.",
    "3. For A gate 2 and B step 2: loud vs quiet call grounded in their temperament.",
    "4. For B steps 3 to 4: name next tools (Two Kinds; Waffle or 九宫格) and one concrete grid fill action.",
    "5. Closing: one priority fix. No camera tip as the headline.",
    "",
    "### Hard bans",
    "Ban camera / lighting / gear / editing-trick / tech-first advice until the relevant checklist gates have been walked and pass/fail is clear.",
    "Students want the problem to be technical; almost always it is positioning. Say that when they ask for lighting first.",
    "Do not invent Jeff niche case studies. Labels like Suggested/draft are not confirmed IP.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: positioning before volume; loud vs quiet routes; grid before inspiration; get seen before trust before deal where relevant.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Bind to fw.content-not-working-checklists. Prefer also fw.two-kinds-student-two-methods, fw.waffle-grid, fw.jiugongge-topic-bingo, fw.positioning-four-questions when in the pack.",
    "",
    "### Evidence binding",
    "Prefer boundNodeIds when in the evidence pack. Sources still come only from probe / probe_jeff.",
    "",
    "### After",
    "End with one direct next question on the first failed or unclear gate.",
  ].join("\n"),
};
