import type { ModulePack } from "@/lib/modules/types";

/**
 * Criticism Armor: stay consistent under hate / 变好羞耻症.
 */
export const CRITICISM_ARMOR_PACK: ModulePack = {
  moduleId: "criticism-armor",
  intakeFields: [
    {
      id: "criticism",
      label: "Criticism you fear or already got",
      placeholder: "Comments, family pushback, self-talk…",
      required: true,
      multiline: true,
    },
    {
      id: "belief",
      label: "What you believe about your work",
      placeholder: "The conviction you do not want to abandon",
      required: true,
      multiline: true,
    },
    {
      id: "consistent",
      label: "What staying consistent looks like this month",
      placeholder: "e.g. 2 posts a week, one Reel Sunday, keep filming",
      required: true,
    },
    {
      id: "shame",
      label: "变好羞耻症 / growth shame notes",
      placeholder: "Optional: where improving publicly feels exposed",
      required: false,
      multiline: true,
    },
  ],
  probeHints: [
    "criticism not failure",
    "变好羞耻症",
    "bianhao",
    "stay consistent",
    "advice vs ego",
    "standpoint",
    "批评不是失败",
    "立场",
    "持续出现",
    "probe_jeff",
  ],
  boundNodeIds: [
    "cl.criticism-not-failure",
    "tm.bianhao-xiuchizheng",
    "pr.advice-vs-ego",
    "pr.standpoint-or-invisible",
    "rj.overnight-fame",
  ],
  starterPrompt:
    "Using my intake, give a short armor plan: what to ignore, what to learn from, and how to keep posting without performing toughness.",
  chatOpener:
    "I will give a short armor plan so criticism does not stop posting. What criticism do you fear or already got?",
  systemOverlay: [
    "## Module mode: Criticism Armor",
    "You are running the Criticism Armor tool for this user.",
    "Job: help them stay consistent when hate, doubt, or 变好羞耻症 shows up after they post.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks over a generic business questionnaire.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "Deliver a short armor plan:",
    "1. Ignore: what is noise (bullets).",
    "2. Learn from: what might be useful signal without abandoning standpoint.",
    "3. Keep posting: a concrete consistency plan matched to their month goal.",
    "4. Shame note: name 变好羞耻症 / growth exposure without toughness theater.",
    "5. Reminder: criticism is not failure; stopping is.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume; value then convert where relevant.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Visibility brings criticism; quitting is the failure mode.",
    "No overnight-fame / viral-as-promise framing as the reason to continue.",
    "Never invent Jeff niche case studies as doctrine.",
    "If KB is thin on a specific criticism type: Generally → Jeff → steer to criticism-not-failure / standpoint / advice-vs-ego.",
    "",
    "### Evidence binding",
    "Prefer: cl.criticism-not-failure, tm.bianhao-xiuchizheng, pr.advice-vs-ego, pr.standpoint-or-invisible, rj.overnight-fame when in the evidence pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the plan",
    "End with one direct question that locks their next post despite the noise.",
  ].join("\n"),
};
