import type { ModulePack } from "@/lib/modules/types";

/**
 * B.R.E.A.K Shield / 评论护盾 (D1 p026). Judgment under criticism; not in-thread reply syntax.
 * Module id kept as criticism-armor for stable routes.
 */
export const CRITICISM_ARMOR_PACK: ModulePack = {
  moduleId: "criticism-armor",
  intakeFields: [
    {
      id: "criticism",
      label: "Criticism you fear or already got",
      placeholder: "Comments, family pushback, self-talk…",
      required: true,
      multiline: true,
    },
    {
      id: "baseline",
      label: "Your baseline (Baselines)",
      placeholder: "What you refuse to abandon about your work",
      required: true,
      multiline: true,
    },
    {
      id: "consistent",
      label: "Keep Going this month",
      placeholder: "e.g. 2 posts a week, one Reel Sunday, keep filming",
      required: true,
    },
    {
      id: "shame",
      label: "变好羞耻症 / growth shame notes (optional)",
      placeholder: "Optional: where improving publicly feels exposed",
      required: false,
      multiline: true,
    },
  ],
  probeHints: [
    "B.R.E.A.K",
    "评论护盾",
    "break shield",
    "criticism not failure",
    "变好羞耻症",
    "bianhao",
    "stay consistent",
    "advice vs ego",
    "standpoint",
    "批评不是失败",
    "立场",
    "持续出现",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.break-shield",
    "cl.criticism-not-failure",
    "tm.bianhao-xiuchizheng",
    "pr.advice-vs-ego",
    "pr.standpoint-or-invisible",
    "rj.overnight-fame",
  ],
  starterPrompt:
    "Using my intake, run B.R.E.A.K Shield: Baselines, Reason, Evidence, Angle, Keep Going so criticism becomes judgment, not emotion.",
  chatOpener:
    "I will run B.R.E.A.K Shield / 评论护盾 so criticism becomes judgment, not emotion. What criticism do you fear or already got?",
  systemOverlay: [
    "## Module mode: B.R.E.A.K Shield / 评论护盾",
    "You are running the B.R.E.A.K Shield tool (catalog id criticism-armor) for this user.",
    "Exact Jeff slide title (AUG-D1 p026): B.R.E.A.K Shield / 评论护盾.",
    "Job: turn criticism into judgment, not emotion.",
    "Steps: Baselines 基本预设, Reason 原因, Evidence 证据, Angle 回应角度, Keep Going 继续行动.",
    "Do not draft 评论回应三句法 reply scripts here; that is a separate module (comment-reply-three-lines).",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "Deliver a short B.R.E.A.K plan:",
    "1. Baselines: what stays fixed.",
    "2. Reason: likely motive behind the comment.",
    "3. Evidence: what is fact vs noise.",
    "4. Angle: respond, ignore, or respond differently.",
    "5. Keep Going: concrete consistency plan for this month.",
    "6. Optional 变好羞耻症 note without toughness theater.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Bind to fw.break-shield. Visibility brings criticism; quitting is the failure mode.",
    "No overnight-fame / viral-as-promise framing as the reason to continue.",
    "Never invent Jeff niche case studies as doctrine.",
    "",
    "### Evidence binding",
    "Prefer: fw.break-shield, cl.criticism-not-failure, tm.bianhao-xiuchizheng, pr.advice-vs-ego, pr.standpoint-or-invisible, rj.overnight-fame when in the pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the plan",
    "End with one direct question that locks their next post despite the noise.",
  ].join("\n"),
};
