import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * Eight Ways to Open: stakeholder Framework Needed PDF tool.
 * Elevated draft doctrine; not approved.
 * Quality Runtime (Q4): Collect → Confirm → Deliver → Refine on hook-line family.
 * Chosen over soundbite-one-liner for this wave (open patterns vs memory one-liner).
 */
export const EIGHT_WAYS_TO_OPEN_PACK: ModulePack = {
  moduleId: "eight-ways-to-open",
  qualityRuntime: true,
  qualityFamily: "hook-line",
  confirmBlurb:
    "Mirror the open plan in 2 to 4 bullets: topic, viewer biggest problem, optional loudest moment, and that you will walk all eight ways. Ask for go-ahead before the dense open set. Do not write a full Reel script.",
  deliverableSectionOrder: [
    "Eight ways in order (line or skip with reason)",
    "Strongest two to film",
    "Loudest-ten-seconds-first edit rule",
    "Named refine levers",
  ],
  refineLevers: [
    "stronger feeling open",
    "clearer argument open",
    "better myth or question open",
    "loudest moment moved front",
    "which of the top two to film first",
  ],
  intakeFields: [
    {
      id: "topic",
      label: "Topic",
      placeholder: "What the video is about",
      required: true,
    },
    {
      id: "viewerProblem",
      label: "Biggest viewer problem",
      placeholder: "Lead with this",
      required: true,
      multiline: true,
    },
    {
      id: "loudestMoment",
      label: "Loudest moment already filmed or planned",
      placeholder: "The ten seconds worth moving to the front",
      required: false,
      multiline: true,
    },
  ],
  qualitySlots: [
    {
      id: "topic",
      label: "Topic",
      criticality: "critical",
      probeHint: "What the video is about in plain words.",
      placeholder: "What the video is about",
      idkOptions: [
        "One tip they already teach weekly (scaffold; they name it).",
        "One story beat from real work (scaffold; they name it).",
        "One myth their market still believes (scaffold; they name it).",
        "Or name the topic in one plain sentence.",
      ],
    },
    {
      id: "viewerProblem",
      label: "Biggest viewer problem",
      criticality: "critical",
      probeHint: "Lead with the viewer biggest problem, not an introduction.",
      placeholder: "Lead with this",
      multiline: true,
      idkOptions: [
        "They open with intros and lose the first three seconds (scaffold; they reword).",
        "They bury the loudest moment later in the cut (scaffold; they reword).",
        "They teach useful tips but never stop the scroll (scaffold; they reword).",
        "Or name the viewer problem in their own words.",
      ],
    },
    {
      id: "audience",
      label: "Who watches",
      criticality: "critical",
      probeHint: "Who should feel spoken to in the first three seconds.",
      placeholder: "Who this open is for",
      idkOptions: [
        "A specific role stuck on this topic (scaffold; they name the role).",
        "Warm followers who already like them but scroll past weak opens (scaffold; they correct).",
        "New viewers who need the problem named in second one (scaffold; they correct).",
        "Or name who watches in their own words.",
      ],
    },
    {
      id: "loudestMoment",
      label: "Loudest moment already filmed or planned",
      criticality: "optional",
      probeHint: "Optional ten seconds worth moving to the front.",
      placeholder: "The ten seconds worth moving to the front",
      multiline: true,
    },
  ],
  idkOptionsBySlotId: {
    topic: [
      "One tip they already teach weekly (scaffold; they name it).",
      "One story beat from real work (scaffold; they name it).",
      "One myth their market still believes (scaffold; they name it).",
      "Or name the topic in one plain sentence.",
    ],
    viewerProblem: [
      "They open with intros and lose the first three seconds (scaffold; they reword).",
      "They bury the loudest moment later in the cut (scaffold; they reword).",
      "They teach useful tips but never stop the scroll (scaffold; they reword).",
      "Or name the viewer problem in their own words.",
    ],
    audience: [
      "A specific role stuck on this topic (scaffold; they name the role).",
      "Warm followers who already like them but scroll past weak opens (scaffold; they correct).",
      "New viewers who need the problem named in second one (scaffold; they correct).",
      "Or name who watches in their own words.",
    ],
  },
  probeHints: [
    "eight ways to open",
    "first three seconds",
    "loudest moment",
    "开场八法",
    "前三秒",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.eight-ways-to-open",
    "fw.hook-formula",
  ],
  starterPrompt:
    "Using my intake, run Eight Ways to Open: one line per way (or skip with reason), mark the strongest two, and apply loudest-ten-seconds-first.",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you try several ways to open the first three seconds of a video.",
    firstAsk: "What topic or current open should we start from?",
    seed: "eight-ways-to-open",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你试几种开场方式，打磨视频前三秒。",
    firstAsk: "从哪个题目或现有开场开始？",
    seed: "eight-ways-to-open",
  }),
  systemOverlay: [
    "## Module mode: Eight Ways to Open (qualityRuntime Hook/Line)",
    "You are running the Eight Ways to Open tool (catalog id eight-ways-to-open) for this user.",
    "Job: Write openings for the first three seconds using the eight ways below, plus loudest-moment-first edit rule. Not a full Reel script.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first eight-way set unless they explicitly say just write it after criticals are filled.",
    "Name while applying: Jeff's <<Eight Ways to Open>> / Jeff 的 <<Eight Ways to Open>> (`fw.eight-ways-to-open`). Apply; do not lecture.",
    "",
    "### The eight openings (paste from Framework Needed; teach by name)",
    "1. Strong feeling",
    "2. An argument",
    "3. A view people fight about",
    "4. Something everyone cares about",
    "5. Breaking the pattern",
    "6. A myth everyone believes",
    "7. An unanswered question",
    "8. Whatever is in the news",
    "",
    "### Edit rule (loudest 10s first)",
    "Edit the whole video first. Find the loudest ten seconds. Move that to the front.",
    "Most students open with what they planned to say, which is almost never the best part.",
    "Lead with the viewer biggest problem, not an introduction. Reject intro-first opens.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: topic, viewer biggest problem, and who watches.",
    "Loudest moment optional.",
    "Ask at most 1 to 2 questions per Collect turn.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent niche facts.",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not walk all eight ways in Confirm.",
    "",
    "### Deliverable shape (opens only)",
    "1. Walk all eight ways in order. For each: one opening line, OR skip with a one-line reason why it does not fit.",
    "2. Mark the strongest two to film (name the way + the line).",
    "3. Restate the edit rule: cut first, move loudest ten seconds to the front.",
    "4. Optional: if they already named a loudest moment, show how it becomes the open.",
    "5. End with named refine levers.",
    "Ground every line in their topic and problem. Different inputs must produce different opens.",
    "",
    "### Refine",
    "After a dense eight-way set exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Bind to fw.eight-ways-to-open. Labels like Suggested/draft are not confirmed IP. Never invent Jeff niche case studies.",
    "Do not rename these eight ways into Hook Formula legs or GOAT beats. Complementary tools stay separate.",
    "No overnight-fame. Do not turn this into a full IG script writer.",
    "",
    "### Evidence binding",
    "Prefer boundNodeIds when in the evidence pack. Sources still come only from probe / probe_jeff.",
    "",
    "### After",
    "End with one direct next question: which of the strongest two they will film first.",
  ].join("\n"),
};
