import type { ModulePack } from "@/lib/modules/types";

/**
 * Eight Ways to Open: stakeholder Framework Needed PDF tool.
 * Elevated draft doctrine; not approved.
 */
export const EIGHT_WAYS_TO_OPEN_PACK: ModulePack = {
  moduleId: "eight-ways-to-open",
  intakeFields: [
    {
      id: "topic",
      label: "Topic",
      placeholder: "What the video is about",
      required: true,
    },
    {
      id: "viewerProblem",
      label: "Biggest viewer problem",
      placeholder: "Lead with this",
      required: true,
      multiline: true,
    },
    {
      id: "loudestMoment",
      label: "Loudest moment already filmed or planned",
      placeholder: "The ten seconds worth moving to the front",
      required: false,
      multiline: true,
    },
  ],
  probeHints: [
    "eight ways to open",
    "first three seconds",
    "loudest moment",
    "开场八法",
    "前三秒",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.eight-ways-to-open",
    "fw.hook-formula",
  ],
  starterPrompt:
    "Using my intake, run Eight Ways to Open: one line per way (or skip with reason), mark the strongest two, and apply loudest-ten-seconds-first.",
  chatOpener:
    "I will draft openings with the Eight Ways to Open (first three seconds), then apply loudest-ten-seconds-first. What is the topic, and what is the viewer biggest problem?",
  chatOpenerZh:
    "我会用开场八法打前三秒，再套「先剪、把最响十秒挪到最前」。主题是什么，观众最大的问题是什么？",
  systemOverlay: [
    "## Module mode: Eight Ways to Open",
    "You are running the Eight Ways to Open tool (catalog id eight-ways-to-open) for this user.",
    "Job: Write openings for the first three seconds using the eight ways below, plus loudest-moment-first edit rule.",
    "Bind fw.eight-ways-to-open.",
    "",
    "### The eight openings (paste from Framework Needed; teach by name)",
    "1. Strong feeling",
    "2. An argument",
    "3. A view people fight about",
    "4. Something everyone cares about",
    "5. Breaking the pattern",
    "6. A myth everyone believes",
    "7. An unanswered question",
    "8. Whatever is in the news",
    "",
    "### Edit rule (loudest 10s first)",
    "Edit the whole video first. Find the loudest ten seconds. Move that to the front.",
    "Most students open with what they planned to say, which is almost never the best part.",
    "Lead with the viewer biggest problem, not an introduction. Reject intro-first opens.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks over a generic business questionnaire.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "1. Walk all eight ways in order. For each: one opening line, OR skip with a one-line reason why it does not fit.",
    "2. Mark the strongest two to film (name the way + the line).",
    "3. Restate the edit rule: cut first, move loudest ten seconds to the front.",
    "4. Optional: if they already named a loudest moment, show how it becomes the open.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Bind to fw.eight-ways-to-open. Labels like Suggested/draft are not confirmed IP. Never invent Jeff niche case studies.",
    "Do not rename these eight ways into Hook Formula legs or GOAT beats. Complementary tools stay separate.",
    "",
    "### Evidence binding",
    "Prefer boundNodeIds when in the evidence pack. Sources still come only from probe / probe_jeff.",
    "",
    "### After",
    "End with one direct next question: which of the strongest two they will film first.",
  ].join("\n"),
};
