import type { ModulePack } from "@/lib/modules/types";

/**
 * CONTENT BANK / 内容库 (AUG-D3): inventory by 题材 / 分类 / 形式 / 状态.
 * Module id kept as faq-content-bank. FAQ questions are one input for 题材 only.
 */
export const FAQ_CONTENT_BANK_PACK: ModulePack = {
  moduleId: "faq-content-bank",
  intakeFields: [
    {
      id: "topicsOrQuestions",
      label: "题材 inputs (problems, views, myths, stories, or FAQ questions)",
      placeholder: "List raw material: questions you hear, views, myths, stories",
      required: true,
      multiline: true,
      helpText: "FAQ questions feed 题材 only. They are not the whole bank job.",
    },
    {
      id: "niche",
      label: "Niche",
      placeholder: "Your space",
      required: true,
    },
    {
      id: "preferredForms",
      label: "Preferred 形式 (optional)",
      placeholder: "口播 / 对谈 / 清单 / 案例 / Vlog",
      required: false,
    },
    {
      id: "statusDefault",
      label: "Default 状态 (optional)",
      placeholder: "e.g. idea, draft, ready to film, published",
      required: false,
    },
    {
      id: "boundaries",
      label: "Answer boundaries",
      placeholder: "What you will not share on camera",
      required: false,
      multiline: true,
    },
  ],
  probeHints: [
    "CONTENT BANK",
    "内容库",
    "题材",
    "分类",
    "形式",
    "状态",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.content-bank",
    "tm.content-asset",
    "pr.exposure-trust-conversion",
    "cl.content-not-ads",
    "pr.direction-beats-volume",
  ],
  starterPrompt:
    "Using my intake, build a CONTENT BANK inventory: for each item tag 题材 / 分类 / 形式 / 状态 using Jeff axes (AUG-D3).",
  chatOpener:
    "I will inventory a CONTENT BANK on Jeff axes: 题材 / 分类 / 形式 / 状态. Paste raw material (questions, views, myths, or stories). FAQ questions count as 题材 inputs only.",
  chatOpenerZh:
    "我会按 Jeff CONTENT BANK（题材 / 分类 / 形式 / 状态）帮你建内容库。把素材贴过来（问题、观点、误区、故事都可以）。FAQ 问题只进题材，不是整套任务。",
  systemOverlay: [
    "## Module mode: CONTENT BANK / 内容库",
    "You are running the CONTENT BANK tool (catalog id faq-content-bank) for this user.",
    "Job: inventory content by Jeff CONTENT BANK axes (AUG-D3). Not an FAQ-only series generator.",
    "",
    "### Named doctrine (AUG-D3, must teach)",
    "Inventory every row with all four axes:",
    "1. 题材: 问题 / 观点 / 误区 / 故事 (FAQ questions are one input into 题材=问题, not the whole job).",
    "2. 分类: 教育 / 信任 / 证明 / 引流 / 转化.",
    "3. 形式: 口播 / 对谈 / 清单 / 案例 / Vlog.",
    "4. 状态: use their status language, or default idea / draft / ready / published.",
    "Bind fw.content-bank.",
    "",
    "### Hard reject",
    "Do NOT invent a see/trust/convert (or exposure/trust/deal) tag scheme for this tool.",
    "Do NOT collapse the job into FAQ titles + 1 to 2 sentence angles only.",
    "Do NOT treat FAQ as the framework name. FAQ is optional raw material for 题材.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks over a generic business questionnaire.",
    "When enough is known, or the user says just write it, deliver the full inventory and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "Table or numbered rows. Each row MUST include:",
    "title/angle, 题材 (one of 问题/观点/误区/故事), 分类 (one of 教育/信任/证明/引流/转化), 形式 (one of 口播/对谈/清单/案例/Vlog), 状态.",
    "Respect answer boundaries. Content assets, not ads.",
    "If workshop CONTENT BANK doctrine is thin: Generally → Jeff → steer.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; direction beats volume.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "No overnight-fame. Never invent Jeff niche case studies as doctrine. Niche answers come from the conversation.",
    "",
    "### Evidence binding",
    "Prefer: fw.content-bank, tm.content-asset, pr.exposure-trust-conversion, cl.content-not-ads, pr.direction-beats-volume when in the pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the bank",
    "End with one direct question: which inventoried row they will film first.",
  ].join("\n"),
};
