import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * First Impression Script: event + viewpoint → discussion → traffic.
 * Workshop-angle thin: Generally → Jeff → steer.
 * Quality Runtime (Q2): Collect → Confirm → Deliver → Refine on script-spoken family.
 * Dense ~60s+ first-impression spoken piece; asset tone, not overnight fame.
 */
export const FIRST_IMPRESSION_SCRIPT_PACK: ModulePack = {
  moduleId: "first-impression-script",
  qualityRuntime: true,
  qualityFamily: "script-spoken",
  confirmBlurb:
    "Mirror the first-impression plan in 2 to 4 bullets: event, viewpoint, who should care, traffic target, language, and any assumptions. Ask for go-ahead before the full dense ~60s+ script.",
  deliverableSectionOrder: [
    "Open: event + viewpoint (timed)",
    "Discussion beat (timed)",
    "Traffic invite soft (timed)",
    "Optional on-screen text",
    "Named refine levers",
  ],
  refineLevers: [
    "sharper viewpoint open",
    "clearer discussion beat",
    "softer traffic invite",
    "tighter on-screen text",
  ],
  intakeFields: [
    {
      id: "event",
      label: "Event or moment",
      placeholder: "Talk, launch, news, industry moment…",
      required: true,
    },
    {
      id: "viewpoint",
      label: "Your viewpoint",
      placeholder: "What you believe about it",
      required: true,
      multiline: true,
    },
    {
      id: "audience",
      label: "Who should care",
      placeholder: "Who this first impression is for",
      required: true,
    },
    {
      id: "trafficTarget",
      label: "Where curious people should go",
      placeholder: "Profile, follow, save, soft invite…",
      required: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: true,
    },
  ],
  qualitySlots: [
    {
      id: "event",
      label: "Event or moment",
      criticality: "critical",
      probeHint: "The talk, launch, news, or industry moment they are reacting to.",
      placeholder: "Talk, launch, news, industry moment…",
      idkOptions: [
        "A talk or workshop they just finished (scaffold; they correct).",
        "A niche news or industry moment this week (scaffold; they correct).",
        "A launch or offer update they need to explain without hard sell (scaffold).",
        "Or name the event in one plain sentence.",
      ],
    },
    {
      id: "viewpoint",
      label: "Your viewpoint",
      criticality: "critical",
      probeHint: "What they believe about the event. Standpoint first.",
      placeholder: "What you believe about it",
      multiline: true,
      idkOptions: [
        "The loud take misses the real mechanism (scaffold; they reword).",
        "People are celebrating the wrong metric (scaffold; they reword).",
        "What matters is ownership of the next practice, not the headline (scaffold).",
        "Or give one viewpoint line they would own on camera.",
      ],
    },
    {
      id: "audience",
      label: "Who should care",
      criticality: "critical",
      probeHint: "Who this first impression is for.",
      placeholder: "Who this first impression is for",
      idkOptions: [
        "Peers in their niche who saw the same moment (scaffold).",
        "Prospects who need a clear stance after the event (scaffold).",
        "Students or clients who need the practical takeaway (scaffold).",
        "Or name who should care in their own words.",
      ],
    },
    {
      id: "trafficTarget",
      label: "Where curious people should go",
      criticality: "critical",
      probeHint: "Soft traffic: profile, follow, save, or light invite.",
      placeholder: "Profile, follow, save, soft invite…",
      idkOptions: [
        "Soft: follow or visit profile for the next tip.",
        "Save this for the checklist after the event.",
        "Light invite: DM a keyword if they want the notes.",
        "Or name where curious people should go next.",
      ],
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "critical",
      probeHint: "Match how they speak on camera: English, Chinese, or mixed.",
      placeholder: "English, Chinese, or mixed",
      idkOptions: [
        "English only, spoken and filmable.",
        "Chinese only, spoken and filmable.",
        "Mixed: Chinese spoken with short English terms they already use.",
      ],
    },
  ],
  idkOptionsBySlotId: {
    event: [
      "A talk or workshop they just finished (scaffold; they correct).",
      "A niche news or industry moment this week (scaffold; they correct).",
      "A launch or offer update they need to explain without hard sell (scaffold).",
      "Or name the event in one plain sentence.",
    ],
    viewpoint: [
      "The loud take misses the real mechanism (scaffold; they reword).",
      "People are celebrating the wrong metric (scaffold; they reword).",
      "What matters is ownership of the next practice, not the headline (scaffold).",
      "Or give one viewpoint line they would own on camera.",
    ],
    audience: [
      "Peers in their niche who saw the same moment (scaffold).",
      "Prospects who need a clear stance after the event (scaffold).",
      "Students or clients who need the practical takeaway (scaffold).",
      "Or name who should care in their own words.",
    ],
    trafficTarget: [
      "Soft: follow or visit profile for the next tip.",
      "Save this for the checklist after the event.",
      "Light invite: DM a keyword if they want the notes.",
      "Or name where curious people should go next.",
    ],
    language: [
      "English only, spoken and filmable.",
      "Chinese only, spoken and filmable.",
      "Mixed: Chinese spoken with short English terms they already use.",
    ],
  },
  probeHints: [
    "standpoint",
    "get seen",
    "exposure trust",
    "content asset",
    "not ads",
    "first impression",
    "第一印象",
    "立场",
    "观点带流量",
    "信任",
    "probe_jeff",
  ],
  boundNodeIds: [
    "pr.standpoint-or-invisible",
    "pr.exposure-trust-conversion",
    "cl.content-not-ads",
    "rj.overnight-fame",
  ],
  starterPrompt:
    "Using my intake, write a dense ~60s+ first-impression script: viewpoint, discussion beat, then light traffic invite. Asset tone, not overnight fame.",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you write a dense first-impression script at about 60 seconds and above that leads with your viewpoint.",
    firstAsk: "What event or moment are you reacting to?",
    seed: "first-impression-script",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你写一条密实第一印象脚本，大约 60 秒及以上，先讲观点。",
    firstAsk: "你在回应的是什么事件或瞬间？",
    seed: "first-impression-script",
  }),
  systemOverlay: [
    "## Module mode: First Impression Script (qualityRuntime Script/Spoken)",
    "You are running the First Impression Script tool for this user.",
    "Job: produce a dense ~60s+ piece: event or viewpoint → discussion → light traffic toward their space.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first full script unless they explicitly say just write it after criticals are filled.",
    "",
    "### Distinct job (not OPENS Reel / not hot take without event / not process proof)",
    "Lead with a clear view on a moment. Invite thinking. Soft traffic only if it fits. Asset tone.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Standpoint or invisible. Get seen before trust before deal. Content assets are not ads.",
    "Reject overnight-fame framing.",
    "ANTI-GENERIC: if it could come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: event, viewpoint, audience, traffic target, language.",
    "Ask at most 1 to 2 questions per Collect turn. Prefer Jeff-shaped asks (viewpoint) over a generic business questionnaire.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent event details.",
    "User owns niche facts. Jeff owns craft (standpoint + soft traffic).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full timed script in Confirm.",
    "",
    "### Deliverable shape (dense; ~60s+)",
    "1. Open: event + viewpoint + approximate seconds.",
    "2. Discussion beat: invite thinking, not rant-only + approximate seconds.",
    "3. Traffic invite: soft, aligned with their target + approximate seconds.",
    "4. Optional on-screen text.",
    "5. End with named refine levers.",
    "Timing should read as about 60 seconds and above.",
    "Ground every beat in their event and viewpoint. Different inputs must produce different scripts.",
    "Write the whole script in the locked UI locale language.",
    "",
    "### Refine",
    "After a dense script exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Hard bans",
    "Reject overnight-fame framing. Never invent Jeff niche case studies as doctrine.",
    "Specific workshop \"first impression\" playbooks may be thin. Generally → Jeff → steer via standpoint, exposure-trust, content-not-ads.",
    "Prefer pr.standpoint-or-invisible, pr.exposure-trust-conversion, cl.content-not-ads, rj.overnight-fame when present.",
    "Sources only from probe / probe_jeff.",
  ].join("\n"),
};
