import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * GOAT Four Beats: stakeholder Framework Needed PDF tool.
 * Elevated draft doctrine; not approved.
 * Quality Runtime (Q2): Collect → Confirm → Deliver → Refine on script-spoken family.
 * Dense ~60s+ GOAT beats; different named beats from OPENS. Do not rename GOAT to OPENS.
 */
export const GOAT_FOUR_BEATS_PACK: ModulePack = {
  moduleId: "goat-four-beats",
  qualityRuntime: true,
  qualityFamily: "script-spoken",
  confirmBlurb:
    "Mirror the GOAT plan in 2 to 4 bullets: topic, viewer problem, one takeaway, language, and any assumptions. Ask for go-ahead before the full dense ~60s+ Grab / Open / Answer / Take away script.",
  deliverableSectionOrder: [
    "G Grab first seconds (timed)",
    "O Open a question (timed)",
    "A Answer without cheat (timed)",
    "T Take away one keep (timed)",
    "Optional note vs OPENS",
    "Named refine levers",
  ],
  refineLevers: [
    "stronger Grab",
    "costlier Open question",
    "clearer Answer",
    "sharper Take away",
  ],
  intakeFields: [
    {
      id: "topic",
      label: "Topic",
      placeholder: "What this video is about",
      required: true,
    },
    {
      id: "viewerProblem",
      label: "Viewer biggest problem",
      placeholder: "Lead with this, not an intro",
      required: true,
      multiline: true,
    },
    {
      id: "oneTakeaway",
      label: "One thing they keep",
      placeholder: "The T beat",
      required: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: true,
    },
  ],
  qualitySlots: [
    {
      id: "topic",
      label: "Topic",
      criticality: "critical",
      probeHint: "What this short video is about in one breath.",
      placeholder: "What this video is about",
      idkOptions: [
        "One stuck habit in their niche (scaffold; they correct).",
        "A myth their audience keeps repeating (scaffold; they correct).",
        "A soft next step they want viewers to try (scaffold; they correct).",
        "Or name the topic in one plain sentence.",
      ],
    },
    {
      id: "viewerProblem",
      label: "Viewer biggest problem",
      criticality: "critical",
      probeHint: "Lead with the viewer problem, not an intro about the speaker.",
      placeholder: "Lead with this, not an intro",
      multiline: true,
      idkOptions: [
        "They know what to do but cannot stick to one system (scaffold).",
        "They feel drowned in tips with no clear first move (scaffold).",
        "They keep copying loud creators and lose their own standpoint (scaffold).",
        "Or name the viewer problem in their own words.",
      ],
    },
    {
      id: "oneTakeaway",
      label: "One thing they keep",
      criticality: "critical",
      probeHint: "The T beat: one keep after Answer.",
      placeholder: "The T beat",
      idkOptions: [
        "One check to run tomorrow morning (scaffold).",
        "One line to say when the myth shows up (scaffold).",
        "One tiny practice for seven days (scaffold).",
        "Or name the one thing viewers should keep.",
      ],
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "critical",
      probeHint: "Match how they speak on camera: English, Chinese, or mixed.",
      placeholder: "English, Chinese, or mixed",
      idkOptions: [
        "English only, spoken and filmable.",
        "Chinese only, spoken and filmable.",
        "Mixed: Chinese spoken with short English terms they already use.",
      ],
    },
  ],
  idkOptionsBySlotId: {
    topic: [
      "One stuck habit in their niche (scaffold; they correct).",
      "A myth their audience keeps repeating (scaffold; they correct).",
      "A soft next step they want viewers to try (scaffold; they correct).",
      "Or name the topic in one plain sentence.",
    ],
    viewerProblem: [
      "They know what to do but cannot stick to one system (scaffold).",
      "They feel drowned in tips with no clear first move (scaffold).",
      "They keep copying loud creators and lose their own standpoint (scaffold).",
      "Or name the viewer problem in their own words.",
    ],
    oneTakeaway: [
      "One check to run tomorrow morning (scaffold).",
      "One line to say when the myth shows up (scaffold).",
      "One tiny practice for seven days (scaffold).",
      "Or name the one thing viewers should keep.",
    ],
    language: [
      "English only, spoken and filmable.",
      "Chinese only, spoken and filmable.",
      "Mixed: Chinese spoken with short English terms they already use.",
    ],
  },
  probeHints: [
    "GOAT",
    "four beats",
    "grab attention",
    "first three seconds",
    "short video",
    "四拍",
    "开场",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.goat-four-beats",
    "fw.eight-ways-to-open",
    "fw.opens-60s-five-act",
  ],
  starterPrompt:
    "Using my intake, run GOAT Four Beats and deliver a dense ~60s+ Grab / Open / Answer / Take away script for this Jeff tool.",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you structure one dense short video at about 60 seconds and above with GOAT beats: Grab, Open, Answer, Take away.",
    firstAsk: "What is the topic?",
    seed: "goat-four-beats",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你用 GOAT 四拍搭一条密实短视频，大约 60 秒及以上：抓注意、打开、回答、带走。",
    firstAsk: "题目是什么？",
    seed: "goat-four-beats",
  }),
  systemOverlay: [
    "## Module mode: GOAT Four Beats (qualityRuntime Script/Spoken)",
    "You are running the GOAT Four Beats tool (catalog id goat-four-beats) for this user.",
    "Name while applying: Jeff's <<GOAT Four Beats>> / Jeff 的 <<GOAT Four Beats>> (`fw.goat-four-beats`). Apply; do not lecture.",
    "Job: Structure one dense short video at about 60 seconds and above as Grab, Open a question, Answer it, Take it away.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first full script unless they explicitly say just write it after criticals are filled.",
    "",
    "### Distinct job (GOAT ≠ OPENS)",
    "Use GOAT named beats only. Do NOT rename GOAT to OPENS. If the user asks about OPENS, name the difference; still deliver GOAT here.",
    "Related to OPENS / Hook Formula; different named beats. Labels like Suggested/draft are not confirmed IP.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume.",
    "ANTI-GENERIC: if it could come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: topic, viewer biggest problem, one takeaway, language.",
    "Ask at most 1 to 2 questions per Collect turn. Lead with viewer problem, not speaker intro.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent niche facts.",
    "User owns niche facts. Jeff owns craft (GOAT beat structure).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full timed script in Confirm.",
    "",
    "### Deliverable shape (dense; ~60s+)",
    "1. G Grab (first seconds line) + approximate seconds.",
    "2. O Open a question (make leaving costly) + approximate seconds.",
    "3. A Answer (no cheat) + approximate seconds.",
    "4. T Take away (one keep) + approximate seconds.",
    "5. Optional note vs OPENS if relevant; do not invent Jeff names.",
    "6. End with named refine levers.",
    "Timing should read as about 60 seconds and above, not a thin three-second Grab only.",
    "Ground every beat in their topic and problem. Different inputs must produce different scripts.",
    "Write the whole script in the locked UI locale language.",
    "",
    "### Refine",
    "After a dense script exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Hard bans",
    "Bind to fw.goat-four-beats. Never invent Jeff niche case studies as doctrine. No overnight-fame.",
    "Prefer boundNodeIds when in the evidence pack. Sources only from probe / probe_jeff.",
  ].join("\n"),
};
