import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * Hot Take Script: sharp standpoint on camera as advice, not ego.
 * Quality Runtime (Q2): Collect → Confirm → Deliver → Refine on script-spoken family.
 * Dense ~60s+ spoken hot take; not outrage bait and not a full OPENS rewrite.
 */
export const HOT_TAKE_SCRIPT_PACK: ModulePack = {
  moduleId: "hot-take-script",
  qualityRuntime: true,
  qualityFamily: "script-spoken",
  confirmBlurb:
    "Mirror the hot-take plan in 2 to 4 bullets: the claim, what it challenges, the practical truth, language, and any assumptions. Ask for go-ahead before the full dense ~60s+ script.",
  deliverableSectionOrder: [
    "Stance open (timed)",
    "Reason beats 2 to 4 (timed)",
    "Landing that protects relationship (timed)",
    "Advice vs ego cut note",
    "Named refine levers",
  ],
  refineLevers: [
    "sharper stance open",
    "stronger reason beats",
    "softer landing",
    "cut ego flex lines",
  ],
  intakeFields: [
    {
      id: "claim",
      label: "The claim you want to make",
      placeholder: "One sharp sentence you are willing to own",
      required: true,
      multiline: true,
    },
    {
      id: "challenges",
      label: "Who or what it challenges",
      placeholder: "Common advice, habit, or soft consensus in your niche",
      required: true,
    },
    {
      id: "truth",
      label: "Practical truth behind the heat",
      placeholder: "Why this helps the viewer, not why it makes you look bold",
      required: true,
      multiline: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: true,
    },
  ],
  qualitySlots: [
    {
      id: "claim",
      label: "The claim you want to make",
      criticality: "critical",
      probeHint: "One sharp sentence they are willing to own on camera.",
      placeholder: "One sharp sentence you are willing to own",
      multiline: true,
      idkOptions: [
        "Motivation speeches fail; small systems win (scaffold; they reword).",
        "Fear content is not proof (scaffold; they reword).",
        "More posting is not the same as clearer standpoint (scaffold; they reword).",
        "Or give one line they would defend on camera.",
      ],
    },
    {
      id: "challenges",
      label: "Who or what it challenges",
      criticality: "critical",
      probeHint: "Common advice, habit, or soft consensus this claim pushes against.",
      placeholder: "Common advice, habit, or soft consensus in your niche",
      idkOptions: [
        "Generic \"just be consistent\" advice with no system (scaffold).",
        "Hype that promises overnight results (scaffold).",
        "Soft consensus that volume alone equals trust (scaffold).",
        "Or name what they are challenging in plain words.",
      ],
    },
    {
      id: "truth",
      label: "Practical truth behind the heat",
      criticality: "critical",
      probeHint: "Why this helps the viewer, not why it makes the speaker look bold.",
      placeholder: "Why this helps the viewer, not why it makes you look bold",
      multiline: true,
      idkOptions: [
        "Viewers need one usable next move, not a flex (scaffold).",
        "Trust grows when the claim names a real stuck point (scaffold).",
        "Heat without service is ego; land a teachable truth (scaffold).",
        "Or say the practical truth in their own words.",
      ],
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "critical",
      probeHint: "Match how they speak on camera: English, Chinese, or mixed.",
      placeholder: "English, Chinese, or mixed",
      idkOptions: [
        "English only, spoken and filmable.",
        "Chinese only, spoken and filmable.",
        "Mixed: Chinese spoken with short English terms they already use.",
      ],
    },
  ],
  idkOptionsBySlotId: {
    claim: [
      "Motivation speeches fail; small systems win (scaffold; they reword).",
      "Fear content is not proof (scaffold; they reword).",
      "More posting is not the same as clearer standpoint (scaffold; they reword).",
      "Or give one line they would defend on camera.",
    ],
    challenges: [
      "Generic \"just be consistent\" advice with no system (scaffold).",
      "Hype that promises overnight results (scaffold).",
      "Soft consensus that volume alone equals trust (scaffold).",
      "Or name what they are challenging in plain words.",
    ],
    truth: [
      "Viewers need one usable next move, not a flex (scaffold).",
      "Trust grows when the claim names a real stuck point (scaffold).",
      "Heat without service is ego; land a teachable truth (scaffold).",
      "Or say the practical truth in their own words.",
    ],
    language: [
      "English only, spoken and filmable.",
      "Chinese only, spoken and filmable.",
      "Mixed: Chinese spoken with short English terms they already use.",
    ],
  },
  probeHints: [
    "standpoint",
    "hot take",
    "advice vs ego",
    "criticism",
    "personal IP",
    "content asset",
    "立场",
    "热观点",
    "建议 vs 自我",
    "批评不是失败",
    "probe_jeff",
  ],
  boundNodeIds: [
    "pr.standpoint-or-invisible",
    "pr.advice-vs-ego",
    "cl.criticism-not-failure",
    "tm.lichang",
  ],
  starterPrompt:
    "Using my intake, write a dense ~60s+ hot-take script with stance, reason, and a landing that protects relationship with the viewer. Keep it advice, not ego.",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you turn a sharp claim into a dense hot-take script at about 60 seconds and above that lands as advice, not a flex.",
    firstAsk: "What claim are you willing to own in one sentence?",
    seed: "hot-take-script",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你把锋利主张写成密实热观点脚本，大约 60 秒及以上，落点是建议，不是炫耀。",
    firstAsk: "你愿意用一句话认领的主张是什么？",
    seed: "hot-take-script",
  }),
  systemOverlay: [
    "## Module mode: Hot Take Script (qualityRuntime Script/Spoken)",
    "You are running the Hot Take Script tool for this user.",
    "Job: produce a dense ~60s+ on-camera hot take that reads as advice, not ego performance.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first full script unless they explicitly say just write it after criticals are filled.",
    "",
    "### Distinct job (not OPENS / not value tip Reel / not process proof)",
    "Standpoint heat with a teachable land. Ban outrage bait with no service. Do not rewrite into a full OPENS five-act unless they ask for a different tool.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Standpoint or invisible. Heat without service is ego. Criticism can come with visibility; quitting is the failure mode.",
    "Land the practical truth for the viewer; protect relationship.",
    "Force an advice-vs-ego check before sending.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: claim, who/what it challenges, practical truth, language.",
    "Ask at most 1 to 2 questions per Collect turn. Ask the claim first when missing.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent niche facts or fake controversy.",
    "User owns niche facts. Jeff owns craft (advice vs ego, landing that protects relationship).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full timed script in Confirm.",
    "",
    "### Deliverable shape (dense; ~60s+)",
    "1. Stance open + approximate seconds.",
    "2. Reason beats (2 to 4) + approximate seconds.",
    "3. Landing that protects relationship + approximate seconds.",
    "4. Advice vs ego note: what to cut if flex sneaks in.",
    "5. End with named refine levers.",
    "Timing should read as about 60 seconds and above unless they ask for a shorter cut after Confirm.",
    "Ground every beat in their claim and truth. Different claims must produce different scripts.",
    "Write the whole script in the locked UI locale language.",
    "",
    "### Refine",
    "After a dense script exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Hard bans",
    "No overnight-fame. No inventing Jeff case studies as doctrine.",
    "Prefer pr.standpoint-or-invisible, pr.advice-vs-ego, cl.criticism-not-failure, tm.lichang when present.",
    "Sources only from probe / probe_jeff. Thin coverage: Generally → Jeff → steer.",
  ].join("\n"),
};
