import type { ModulePack } from "@/lib/modules/types";

/**
 * IG Reel Script pack: shootable 15-45s Reel as a content asset, not a hard-sell ad.
 * Binds preference to short-video / value-then-convert / content-not-ads / exposure-trust nodes.
 */
export const IG_REEL_SCRIPT_PACK: ModulePack = {
  moduleId: "ig-reel-script",
  intakeFields: [
    {
      id: "niche",
      label: "Niche or industry",
      placeholder: "e.g. boutique fitness, B2B SaaS, family law clinic",
      required: true,
      helpText: "What space you work in. You fill niche facts; Jeff craft stays on IP and content assets.",
    },
    {
      id: "audience",
      label: "Audience",
      placeholder: "Who should stop scrolling and feel spoken to?",
      required: true,
    },
    {
      id: "standpoint",
      label: "Standpoint or offer angle",
      placeholder: "One sharp line you stand for, or the offer angle without hard pitch",
      required: true,
      helpText: "Standpoint first. Offer is optional context, not a sales script.",
    },
    {
      id: "lesson",
      label: "One lesson or story beat",
      placeholder: "The single tip or moment you will teach in this Reel",
      required: true,
      multiline: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed (match how you speak on camera)",
      required: true,
    },
    {
      id: "ctaSoftness",
      label: "CTA softness",
      placeholder: "Soft (follow/save), medium (DM keyword), or light invite to talk",
      required: false,
      helpText: "Keep the close as an invite, not overnight-fame or hard-sell pressure.",
    },
  ],
  probeHints: [
    "Instagram Reel",
    "short video",
    "content asset",
    "not ads",
    "value then convert",
    "exposure trust",
    "get seen",
    "hook",
    "personal IP",
    "曝光",
    "信任",
    "成交",
    "内容资产",
    "不是广告",
    "立场",
    "先给价值",
    "probe_jeff",
  ],
  boundNodeIds: [
    "pr.exposure-trust-conversion",
    "cl.short-vs-long-video",
    "cl.content-not-ads",
    "cl.value-then-convert",
    "pr.standpoint-or-invisible",
    "pr.advice-vs-ego",
  ],
  starterPrompt:
    "Using my intake, write a shootable 15 to 45 second Instagram Reel script: hook, body beats, close, and on-screen text. Keep it a content asset, not a hard-sell ad.",
  chatOpener:
    "I will write you a shootable 15 to 45 second Instagram Reel as a content asset, not a hard-sell ad. What is the one lesson or story beat you want them to take away?",
  systemOverlay: [
    "## Module mode: IG Reel Script",
    "You are running the IG Reel Script tool for this user.",
    "Job: produce a shootable 15 to 45 second Instagram Reel script they can film this week.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Frame the Reel as a content asset on the get-seen → trust → deal chain. Opening earns attention; body teaches or proves standpoint; close invites lightly.",
    "Name the mechanism in their language: content assets are not ads; value then convert; standpoint or invisible; advice vs ego on camera.",
    "If a draft sounds like a hard-sell ad or generic \"build your personal brand\" tips, rewrite toward asset + Jeff mechanisms before sending.",
    "",
    "### Conversational collect (before full script)",
    "Need enough on: niche, audience, standpoint/offer angle, one lesson/story beat, language, CTA softness.",
    "Ask at most 1 to 2 questions per turn. Prefer Jeff-shaped asks (standpoint, lesson beat) over \"tell me about your business\".",
    "When enough is known, or they say just write it, deliver the full script and name assumptions.",
    "",
    "### Output shape (few-shot of structure)",
    "1. Hook (1 to 3s): scroll-stop line on camera.",
    "2. Body beats (2 to 4): speakable teaching or story; each beat advances trust or standpoint.",
    "3. Close: soft invite (follow, save, DM keyword, light talk), not overnight-fame pressure.",
    "4. On-screen text: short cues per beat.",
    "Optional timing so total stays about 15 to 45 seconds.",
    "Write the whole script in the locked UI locale language.",
    "",
    "### Hard bans",
    "No overnight-fame promises. No inventing Jeff patient/clinic/workshop case studies as doctrine.",
    "Niche facts from the user. Label practice structure for THEIR work when niche-specific.",
    "Sources only from probe / probe_jeff. Prefer pr.exposure-trust-conversion, cl.short-vs-long-video, cl.content-not-ads, cl.value-then-convert, pr.standpoint-or-invisible, pr.advice-vs-ego when present.",
    "Thin coverage: Generally → Jeff → steer, still Jeff-aide voice.",
    "",
    "### After the script",
    "End with one direct question that helps them film or tighten the next draft.",
  ].join("\n"),
};
