import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * IG Reel Script pack: shootable ~60s+ Reel as a content asset, not a hard-sell ad.
 * Preferred scaffold: OPENS 60秒五幕剧 (Opening / Problem / Evidence / New Way / Step).
 * Quality Runtime (Q1): Collect → Confirm → Deliver → Refine on script-spoken family.
 * Do not rename OPENS to GOAT.
 */
export const IG_REEL_SCRIPT_PACK: ModulePack = {
  moduleId: "ig-reel-script",
  qualityRuntime: true,
  qualityFamily: "script-spoken",
  confirmBlurb:
    "Mirror the Reel plan in 2 to 4 bullets: niche and audience, the one lesson or story beat, OPENS five-beat shape at about 60 seconds and above, soft Step style, and any assumptions. Ask for go-ahead before the full dense script.",
  deliverableSectionOrder: [
    "Opening 开场 (timed)",
    "Problem 问题 (timed)",
    "Evidence 证据 (timed)",
    "New Way 新解 (timed)",
    "Step 下一步 (timed soft invite)",
    "On-screen text cues",
    "Optional 四种内容资产 tag",
    "Named refine levers",
  ],
  refineLevers: [
    "tighter Opening",
    "sharper Problem",
    "stronger Evidence",
    "clearer New Way",
    "softer Step",
    "tighter on-screen text",
  ],
  intakeFields: [
    {
      id: "niche",
      label: "Niche or industry",
      placeholder: "e.g. Type 1 diabetes education, boutique fitness, family law clinic",
      required: true,
      helpText: "What space you work in. You fill niche facts; Jeff craft stays on IP and content assets.",
    },
    {
      id: "audience",
      label: "Audience",
      placeholder: "Who should stop scrolling and feel spoken to?",
      required: true,
    },
    {
      id: "standpoint",
      label: "Standpoint or offer angle",
      placeholder: "One sharp line you stand for, or the offer angle without hard pitch",
      required: true,
      helpText: "Standpoint first. Offer is optional context, not a sales script.",
    },
    {
      id: "lesson",
      label: "One lesson or story beat",
      placeholder: "The single tip or moment you will teach in this Reel",
      required: true,
      multiline: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed (match how you speak on camera)",
      required: true,
    },
    {
      id: "ctaSoftness",
      label: "Soft close preference",
      placeholder: "Soft (follow/save), medium (DM keyword), or light invite to talk",
      required: true,
      helpText: "Keep the close as an invite, not overnight-fame or hard-sell pressure.",
    },
    {
      id: "assetType",
      label: "四种内容资产 type (optional)",
      placeholder: "曝光 / 认知 / 信任 / 成交",
      required: false,
      helpText: "Optional one-type tag so the Reel knows its place. Assets are not ads.",
    },
  ],
  qualitySlots: [
    {
      id: "niche",
      label: "Niche or industry",
      criticality: "critical",
      probeHint: "Ask what space they teach in. They own niche facts; do not invent medical details.",
      placeholder: "e.g. Type 1 diabetes education, boutique fitness, family law clinic",
      helpText: "What space you work in. You fill niche facts; Jeff craft stays on IP and content assets.",
      idkOptions: [
        "Living with Type 1 diabetes education (scaffold only; they correct the exact niche).",
        "Caregiver or family support content (scaffold only).",
        "Clinic educator or coach angle (scaffold only).",
        "Or name the niche in one plain sentence of their own.",
      ],
    },
    {
      id: "audience",
      label: "Audience",
      criticality: "critical",
      probeHint: "Who should feel spoken to in the first seconds?",
      placeholder: "Who should stop scrolling and feel spoken to?",
      idkOptions: [
        "Newly diagnosed adults who feel overwhelmed (scaffold; they correct).",
        "Parents or partners supporting someone with Type 1 (scaffold; they correct).",
        "People who already know basics but keep slipping on daily habits (scaffold; they correct).",
        "Or name the audience in their own words.",
      ],
    },
    {
      id: "standpoint",
      label: "Standpoint or offer angle",
      criticality: "critical",
      probeHint: "One sharp line they stand for. Standpoint first; offer is optional context.",
      placeholder: "One sharp line you stand for, or the offer angle without hard pitch",
      helpText: "Standpoint first. Offer is optional context, not a sales script.",
      idkOptions: [
        "Small daily systems beat motivation speeches (scaffold; they reword).",
        "Proof from lived practice, not fear content (scaffold; they reword).",
        "Teach the mechanism, then invite a soft next step (scaffold; they reword).",
        "Or give one line they would defend on camera.",
      ],
    },
    {
      id: "lesson",
      label: "One lesson or story beat",
      criticality: "critical",
      probeHint: "The single tip or lived moment this Reel will teach.",
      placeholder: "The single tip or moment you will teach in this Reel",
      multiline: true,
      idkOptions: [
        "One daily habit that quietly fails, and the fix that actually sticks (scaffold).",
        "A common myth in their niche, then the clearer New Way (scaffold).",
        "A short lived beat: what went wrong, what they changed, what viewers can try (scaffold).",
        "Or share one concrete story beat in their own words.",
      ],
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "critical",
      probeHint: "Match how they speak on camera: English, Chinese, or mixed.",
      placeholder: "English, Chinese, or mixed (match how you speak on camera)",
      idkOptions: [
        "English only, spoken and filmable.",
        "Chinese only, spoken and filmable.",
        "Mixed: Chinese spoken with short English terms they already use.",
      ],
    },
    {
      id: "ctaSoftness",
      label: "Soft close preference",
      criticality: "critical",
      probeHint: "How soft should Step be: follow/save, DM keyword, or light invite to talk?",
      placeholder: "Soft (follow/save), medium (DM keyword), or light invite to talk",
      helpText: "Keep the close as an invite, not overnight-fame or hard-sell pressure.",
      idkOptions: [
        "Soft: follow or save for the next tip.",
        "Medium: DM a simple keyword for a checklist.",
        "Light invite: comment or reply if this is their stuck point.",
      ],
    },
    {
      id: "assetType",
      label: "四种内容资产 type (optional)",
      criticality: "optional",
      probeHint: "Optional one tag: 曝光 / 认知 / 信任 / 成交. Assets are not ads.",
      placeholder: "曝光 / 认知 / 信任 / 成交",
      helpText: "Optional one-type tag so the Reel knows its place. Assets are not ads.",
      idkOptions: [
        "曝光: get seen with a sharp Opening.",
        "认知: teach one clear New Way.",
        "信任: lean on Evidence and lived proof.",
        "成交: still soft Step; never overnight-fame pressure.",
      ],
    },
  ],
  idkOptionsBySlotId: {
    niche: [
      "Living with Type 1 diabetes education (scaffold only; they correct the exact niche).",
      "Caregiver or family support content (scaffold only).",
      "Clinic educator or coach angle (scaffold only).",
      "Or name the niche in one plain sentence of their own.",
    ],
    audience: [
      "Newly diagnosed adults who feel overwhelmed (scaffold; they correct).",
      "Parents or partners supporting someone with Type 1 (scaffold; they correct).",
      "People who already know basics but keep slipping on daily habits (scaffold; they correct).",
      "Or name the audience in their own words.",
    ],
    standpoint: [
      "Small daily systems beat motivation speeches (scaffold; they reword).",
      "Proof from lived practice, not fear content (scaffold; they reword).",
      "Teach the mechanism, then invite a soft next step (scaffold; they reword).",
      "Or give one line they would defend on camera.",
    ],
    lesson: [
      "One daily habit that quietly fails, and the fix that actually sticks (scaffold).",
      "A common myth in their niche, then the clearer New Way (scaffold).",
      "A short lived beat: what went wrong, what they changed, what viewers can try (scaffold).",
      "Or share one concrete story beat in their own words.",
    ],
    language: [
      "English only, spoken and filmable.",
      "Chinese only, spoken and filmable.",
      "Mixed: Chinese spoken with short English terms they already use.",
    ],
    ctaSoftness: [
      "Soft: follow or save for the next tip.",
      "Medium: DM a simple keyword for a checklist.",
      "Light invite: comment or reply if this is their stuck point.",
    ],
  },
  probeHints: [
    "OPENS",
    "60秒五幕剧",
    "short video",
    "content asset",
    "Instagram Reel",
    "不是广告",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.opens-60s-five-act",
    "fw.four-content-assets",
    "pr.exposure-trust-conversion",
    "cl.short-vs-long-video",
    "cl.content-not-ads",
    "cl.value-then-convert",
    "pr.standpoint-or-invisible",
    "pr.advice-vs-ego",
  ],
  starterPrompt:
    "Using my intake, write a shootable Instagram Reel script about 60 seconds and above on OPENS (Opening / Problem / Evidence / New Way / Step). Keep it a content asset, not a hard-sell ad.",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you write a shootable Instagram Reel, about 60 seconds and above, as a teaching asset, not a hard-sell ad.",
    firstAsk: "What is the one lesson or story beat you want them to take away?",
    seed: "ig-reel-script",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你写一条能直接拍的 Instagram Reel，大约 60 秒及以上，当教学资产，不当硬广。",
    firstAsk: "你希望观众带走的那个教训或故事节拍是什么？",
    seed: "ig-reel-script",
  }),
  systemOverlay: [
    "## Module mode: IG Reel Script (qualityRuntime Script/Spoken)",
    "You are running the IG Reel Script tool for this user.",
    "Job: produce a dense, shootable Instagram Reel script at about 60 seconds and above that they can film this week.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first full script unless they explicitly say just write it after criticals are filled.",
    "",
    "### Preferred scaffold (AUG-D2): OPENS 60秒五幕剧",
    "Name while applying: Jeff's <<OPENS 60s Five Act>> / Jeff 的 <<OPENS 60秒五幕>> (`fw.opens-60s-five-act`). Apply; do not lecture.",
    "Structure the Reel as five timed beats totaling about 60 seconds and above:",
    "1. Opening 开场",
    "2. Problem 问题",
    "3. Evidence 证据",
    "4. New Way 新解",
    "5. Step 下一步",
    "Do NOT rename OPENS to GOAT. GOAT is a separate stakeholder tool. If the user asks about GOAT, name the difference; still deliver OPENS here.",
    "Reject unbound hook / body / close-only doctrine as the primary scaffold.",
    "Reject thin 15 to 45 second cuts as the default. Default density is ~60s+ with speakable lines per beat.",
    "",
    "### Optional asset type tag",
    "If known, tag exactly one 四种内容资产 type: 曝光 / 认知 / 信任 / 成交.",
    "Assets are not ads. Do not turn the Reel into a hard-sell ad because a 成交 tag is present.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Frame the Reel as a content asset on the get-seen → trust → deal chain.",
    "Name the mechanism in their language: content assets are not ads; value then convert; standpoint or invisible; advice vs ego on camera.",
    "If a draft sounds like a hard-sell ad or generic \"build your personal brand\" tips, rewrite toward asset + Jeff mechanisms before sending.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: niche, audience, standpoint/offer angle, one lesson/story beat, language, soft close preference.",
    "Optional: 四种内容资产 type.",
    "Ask at most 1 to 2 questions per Collect turn. Prefer Jeff-shaped asks (standpoint, lesson beat) over \"tell me about your business\".",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent medical niche facts, patient names, or private proof.",
    "User owns niche facts. Jeff owns craft (OPENS structure, asset framing, soft Step).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full timed script in Confirm.",
    "",
    "### Deliverable shape (dense; ~60s+)",
    "1. Opening 开场: first-second attention + approximate seconds.",
    "2. Problem 问题: viewer problem on camera + approximate seconds.",
    "3. Evidence 证据: proof, story beat, or lived detail + approximate seconds.",
    "4. New Way 新解: the teaching or standpoint shift + approximate seconds.",
    "5. Step 下一步: soft invite (follow, save, DM keyword, light talk), not overnight-fame pressure + approximate seconds.",
    "6. On-screen text: short cues per beat.",
    "7. Optional: one 四种内容资产 tag for the whole Reel.",
    "8. End with named refine levers (tighter Opening, stronger Evidence, softer Step, and so on).",
    "Timing across beats should read as about 60 seconds and above, not a thin short cut. Spoken volume must match: EN ~130 to 160 words for ~60s; ZH ~220 to 280 characters for ~60s.",
    "Ground every beat in their concrete answers. Different inputs must produce different scripts.",
    "Write the whole script in the locked UI locale language.",
    "",
    "### Refine",
    "After a dense script exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Hard bans",
    "No overnight-fame promises. No inventing Jeff patient/clinic/workshop case studies as doctrine.",
    "Niche facts from the user. Label practice structure for THEIR work when niche-specific.",
    "Sources only from probe / probe_jeff. Prefer fw.opens-60s-five-act, fw.four-content-assets, pr.exposure-trust-conversion, cl.short-vs-long-video, cl.content-not-ads, cl.value-then-convert, pr.standpoint-or-invisible, pr.advice-vs-ego when present.",
    "Thin coverage: Generally → Jeff → steer, still Jeff-aide voice.",
  ].join("\n"),
};
