import type { ModulePack } from "@/lib/modules/types";

/**
 * IG Reel Script pack: shootable 15-45s Reel as a content asset, not a hard-sell ad.
 * Preferred scaffold: OPENS 60秒五幕剧 (Opening / Problem / Evidence / New Way / Step).
 * Do not rename OPENS to GOAT.
 */
export const IG_REEL_SCRIPT_PACK: ModulePack = {
  moduleId: "ig-reel-script",
  intakeFields: [
    {
      id: "niche",
      label: "Niche or industry",
      placeholder: "e.g. boutique fitness, B2B SaaS, family law clinic",
      required: true,
      helpText: "What space you work in. You fill niche facts; Jeff craft stays on IP and content assets.",
    },
    {
      id: "audience",
      label: "Audience",
      placeholder: "Who should stop scrolling and feel spoken to?",
      required: true,
    },
    {
      id: "standpoint",
      label: "Standpoint or offer angle",
      placeholder: "One sharp line you stand for, or the offer angle without hard pitch",
      required: true,
      helpText: "Standpoint first. Offer is optional context, not a sales script.",
    },
    {
      id: "lesson",
      label: "One lesson or story beat",
      placeholder: "The single tip or moment you will teach in this Reel",
      required: true,
      multiline: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed (match how you speak on camera)",
      required: true,
    },
    {
      id: "assetType",
      label: "四种内容资产 type (optional)",
      placeholder: "曝光 / 认知 / 信任 / 成交",
      required: false,
      helpText: "Optional one-type tag so the Reel knows its place. Assets are not ads.",
    },
    {
      id: "ctaSoftness",
      label: "CTA softness",
      placeholder: "Soft (follow/save), medium (DM keyword), or light invite to talk",
      required: false,
      helpText: "Keep the close as an invite, not overnight-fame or hard-sell pressure.",
    },
  ],
  probeHints: [
    "OPENS",
    "60秒五幕剧",
    "short video",
    "content asset",
    "Instagram Reel",
    "不是广告",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.opens-60s-five-act",
    "fw.four-content-assets",
    "pr.exposure-trust-conversion",
    "cl.short-vs-long-video",
    "cl.content-not-ads",
    "cl.value-then-convert",
    "pr.standpoint-or-invisible",
    "pr.advice-vs-ego",
  ],
  starterPrompt:
    "Using my intake, write a shootable 15 to 45 second Instagram Reel script on OPENS (Opening / Problem / Evidence / New Way / Step). Keep it a content asset, not a hard-sell ad.",
  chatOpener:
    "I will write a shootable 15 to 45 second Instagram Reel using OPENS 60秒五幕剧 (Opening / Problem / Evidence / New Way / Step), as a content asset, not a hard-sell ad. What is the one lesson or story beat you want them to take away?",
  chatOpenerZh:
    "我会用 OPENS 60秒五幕剧（Opening / Problem / Evidence / New Way / Step）写一条可拍的 15 到 45 秒 Instagram Reel，当内容资产，不当硬广。你希望观众带走的那一个教训或故事点是什么？",
  systemOverlay: [
    "## Module mode: IG Reel Script",
    "You are running the IG Reel Script tool for this user.",
    "Job: produce a shootable 15 to 45 second Instagram Reel script they can film this week.",
    "",
    "### Preferred scaffold (AUG-D2): OPENS 60秒五幕剧",
    "Bind fw.opens-60s-five-act. Structure the Reel as five beats (scale timing to 15 to 45s):",
    "1. Opening 开场",
    "2. Problem 问题",
    "3. Evidence 证据",
    "4. New Way 新解",
    "5. Step 下一步",
    "Do NOT rename OPENS to GOAT. GOAT is a separate stakeholder tool. If the user asks about GOAT, name the difference; still deliver OPENS here.",
    "Reject unbound hook / body / close-only doctrine as the primary scaffold.",
    "",
    "### Optional asset type tag",
    "If known, tag exactly one 四种内容资产 type: 曝光 / 认知 / 信任 / 成交.",
    "Assets are not ads. Do not turn the Reel into a hard-sell ad because a 成交 tag is present.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Frame the Reel as a content asset on the get-seen → trust → deal chain.",
    "Name the mechanism in their language: content assets are not ads; value then convert; standpoint or invisible; advice vs ego on camera.",
    "If a draft sounds like a hard-sell ad or generic \"build your personal brand\" tips, rewrite toward asset + Jeff mechanisms before sending.",
    "",
    "### Conversational collect (before full script)",
    "Need enough on: niche, audience, standpoint/offer angle, one lesson/story beat, language; optional asset type and CTA softness.",
    "Ask at most 1 to 2 questions per turn. Prefer Jeff-shaped asks (standpoint, lesson beat) over \"tell me about your business\".",
    "When enough is known, or they say just write it, deliver the full script and name assumptions.",
    "",
    "### Output shape",
    "1. Opening 开场: first-second attention.",
    "2. Problem 问题: viewer problem on camera.",
    "3. Evidence 证据: proof, story beat, or lived detail.",
    "4. New Way 新解: the teaching or standpoint shift.",
    "5. Step 下一步: soft invite (follow, save, DM keyword, light talk), not overnight-fame pressure.",
    "6. On-screen text: short cues per beat.",
    "7. Optional: one 四种内容资产 tag for the whole Reel.",
    "Optional timing so total stays about 15 to 45 seconds.",
    "Write the whole script in the locked UI locale language.",
    "",
    "### Hard bans",
    "No overnight-fame promises. No inventing Jeff patient/clinic/workshop case studies as doctrine.",
    "Niche facts from the user. Label practice structure for THEIR work when niche-specific.",
    "Sources only from probe / probe_jeff. Prefer fw.opens-60s-five-act, fw.four-content-assets, pr.exposure-trust-conversion, cl.short-vs-long-video, cl.content-not-ads, cl.value-then-convert, pr.standpoint-or-invisible, pr.advice-vs-ego when present.",
    "Thin coverage: Generally → Jeff → steer, still Jeff-aide voice.",
    "",
    "### After the script",
    "End with one direct question that helps them film or tighten the next draft.",
  ].join("\n"),
};
