import type { ModulePack } from "@/lib/modules/types";

/**
 * Brand Pillars (Jeff AUG-D1 p049 four-step method).
 * Module id kept as ip-pillars for stable routes.
 */
export const IP_PILLARS_PACK: ModulePack = {
  moduleId: "ip-pillars",
  intakeFields: [
    {
      id: "whoAndPain",
      label: "WHO + 痛点",
      placeholder: "Who you serve and the pain they feel (plain words)",
      required: true,
      multiline: true,
    },
    {
      id: "marketQuestions",
      label: "10 market questions",
      placeholder: "List 10 questions the market asks most often (must reach 10 before pillars)",
      required: true,
      multiline: true,
      helpText: "Refuse full pillars until exactly these are listed as 10 distinct market questions.",
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: false,
    },
  ],
  probeHints: [
    "brand pillars",
    "Brand Pillars",
    "10个问题",
    "痛点",
    "支柱",
    "内容支柱",
    "归类",
    "主题",
    "WHO",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.brand-pillars",
    "pr.direction-beats-volume",
    "rj.volume-equals-money",
  ],
  starterPrompt:
    "Using my intake, run Jeff Brand Pillars four steps: WHO+痛点, list 10 market questions, cluster to 3 to 5 themes, then durable pillars. Do not deliver pillars until 10 questions exist. Do not use see/trust/convert rotation.",
  chatOpener:
    "I will run Jeff Brand Pillars in four steps: WHO+痛点, list 10 market questions, cluster to 3 to 5, then durable pillars. Who do you serve, and what pain do they feel?",
  chatOpenerZh:
    "我会按 Jeff Brand Pillars 四步走：WHO+痛点 → 列10个市场问题 → 归成3到5组 → 留成长期支柱。先说你服务谁、他们的痛点是什么？",
  systemOverlay: [
    "## Module mode: Brand Pillars",
    "You are running the Brand Pillars tool (catalog id ip-pillars) for this user.",
    "Jeff binding: fw.brand-pillars (AUG-D1 p049 Brand Pillars 怎么来：4步).",
    "Job: form 3 to 5 durable content pillars by clustering market questions. Pillars = clusters of those questions.",
    "",
    "### Forced Jeff 4 steps (in order)",
    "1) 定义 WHO（服务谁、痛点）.",
    "2) 列10个问题（市场最常问）. Must be ten distinct market questions.",
    "3) 归类成3到5组大主题.",
    "4) 留成支柱（长期可复用栏目）.",
    "Do not skip or reorder these steps.",
    "",
    "### Gate (hard)",
    "REFUSE the full pillar deliverable until 10 market questions exist in the conversation.",
    "If the user has fewer than 10, keep collecting or helping them expand to 10. You may draft candidate questions with them, but do not present final named pillars as done.",
    "When they say just write it without 10 questions: still refuse pillars; ask for or co-draft the missing questions first.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks: who + pain first, then market questions, then cluster.",
    "",
    "### Output format (only after 10 questions exist)",
    "1. WHO + 痛点 (restated).",
    "2. The 10 market questions (numbered).",
    "3. Clusters: 3 to 5 theme groups, each listing which questions belong.",
    "4. Durable pillars: short titles for those clusters (long-term reusable columns).",
    "5. Under each pillar: 1 to 2 example post angles drawn from its questions.",
    "6. Reject volume-equals-money: pillars beat random posting volume.",
    "",
    "### Hard bans",
    "BAN see / trust / convert rotation inside this pack. That path belongs elsewhere; do not teach pillar rotation as see→trust→convert.",
    "Do not invent extra Jeff pillar brand names beyond what the user's questions support.",
    "No overnight-fame. Never invent Jeff niche case studies as doctrine.",
    "",
    "### Jeff distinctiveness (hard)",
    "Direction beats volume. Pillars come from market questions, not from a generic content calendar template.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Evidence binding",
    "Prefer: fw.brand-pillars, pr.direction-beats-volume, rj.volume-equals-money when in the pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the pillars",
    "End with one direct question: which pillar they will film from this week.",
  ].join("\n"),
};
