import type { ModulePack } from "@/lib/modules/types";

/**
 * Long Video Trust Script: trust-path outline bound to Trust Evidence /
 * 信任复利公式 / Trust Engine. Not stock YouTube boilerplate.
 * Quality Runtime (Q2): Collect → Confirm → Deliver → Refine on script-spoken family.
 * Longer than Reel default: 5 to 15 minutes. Do not shrink to 15s ads.
 */
export const LONG_VIDEO_TRUST_SCRIPT_PACK: ModulePack = {
  moduleId: "long-video-trust-script",
  qualityRuntime: true,
  qualityFamily: "script-spoken",
  confirmBlurb:
    "Mirror the long trust-path plan in 2 to 4 bullets: topic, audience, example, trust outcome, Trust Evidence types, language, and any assumptions. Ask for go-ahead before the full dense 5 to 15 minute outline.",
  deliverableSectionOrder: [
    "Open: why this matters for trust",
    "Teaching sections 3 to 5 (speakable)",
    "Trust Evidence placement (结果/过程/角色/人品)",
    "Example placement from their practice",
    "Optional compound note",
    "Soft close",
    "Named refine levers",
  ],
  refineLevers: [
    "stronger open",
    "clearer teaching section",
    "richer Trust Evidence placement",
    "sharper example beat",
    "softer close",
  ],
  intakeFields: [
    {
      id: "topic",
      label: "Topic you can teach 5 to 15 minutes",
      placeholder: "One topic with real depth",
      required: true,
    },
    {
      id: "audience",
      label: "Who it helps",
      placeholder: "Audience for this teach",
      required: true,
    },
    {
      id: "example",
      label: "Story or example from your practice",
      placeholder: "Yours or a permitted paraphrase; not Jeff patient scripts",
      required: true,
      multiline: true,
    },
    {
      id: "trustOutcome",
      label: "Trust outcome you want",
      placeholder: "What belief or confidence should they leave with?",
      required: true,
    },
    {
      id: "evidenceTypes",
      label: "Trust Evidence you can show (结果/过程/角色/人品)",
      placeholder: "Which of 结果 / 过程 / 角色 / 人品 can you prove on camera?",
      required: true,
      multiline: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: true,
    },
  ],
  qualitySlots: [
    {
      id: "topic",
      label: "Topic you can teach 5 to 15 minutes",
      criticality: "critical",
      probeHint: "One topic with real depth, not fluff.",
      placeholder: "One topic with real depth",
      idkOptions: [
        "A mechanism their audience misunderstands (scaffold; they correct).",
        "A practice they already teach live for 10+ minutes (scaffold; they correct).",
        "A trust gap short clips cannot hold (scaffold; they correct).",
        "Or name the topic in one plain sentence.",
      ],
    },
    {
      id: "audience",
      label: "Who it helps",
      criticality: "critical",
      probeHint: "Who this longer teach is for.",
      placeholder: "Audience for this teach",
      idkOptions: [
        "People who already watched short tips but still do not trust judgment (scaffold).",
        "Prospects comparing options and needing depth (scaffold).",
        "Peers who need a clearer shared language (scaffold).",
        "Or name who it helps in their own words.",
      ],
    },
    {
      id: "example",
      label: "Story or example from your practice",
      criticality: "critical",
      probeHint: "Theirs or a permitted paraphrase; never invent Jeff patient scripts.",
      placeholder: "Yours or a permitted paraphrase; not Jeff patient scripts",
      multiline: true,
      idkOptions: [
        "One anonymized practice beat from their work (scaffold; they fill facts).",
        "A before/after of a process they can show (scaffold; they fill facts).",
        "A decision story that proved their standpoint (scaffold; they fill facts).",
        "Or share one concrete example in their own words.",
      ],
    },
    {
      id: "trustOutcome",
      label: "Trust outcome you want",
      criticality: "critical",
      probeHint: "What belief or confidence should viewers leave with?",
      placeholder: "What belief or confidence should they leave with?",
      idkOptions: [
        "They trust the speaker's judgment on this topic (scaffold).",
        "They can name the mechanism in their own words (scaffold).",
        "They feel ready to ask a soft next question (scaffold).",
        "Or name the trust outcome they want.",
      ],
    },
    {
      id: "evidenceTypes",
      label: "Trust Evidence you can show (结果/过程/角色/人品)",
      criticality: "critical",
      probeHint: "Which of 结果 / 过程 / 角色 / 人品 can they prove on camera?",
      placeholder: "Which of 结果 / 过程 / 角色 / 人品 can you prove on camera?",
      multiline: true,
      idkOptions: [
        "结果证据: one outcome they can show without inventing numbers.",
        "过程证据: one process step they can film.",
        "角色证据: why they are the right person to teach this.",
        "人品证据: a boundary or care habit they keep.",
      ],
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "critical",
      probeHint: "Match how they speak on camera: English, Chinese, or mixed.",
      placeholder: "English, Chinese, or mixed",
      idkOptions: [
        "English only, spoken and filmable.",
        "Chinese only, spoken and filmable.",
        "Mixed: Chinese spoken with short English terms they already use.",
      ],
    },
  ],
  idkOptionsBySlotId: {
    topic: [
      "A mechanism their audience misunderstands (scaffold; they correct).",
      "A practice they already teach live for 10+ minutes (scaffold; they correct).",
      "A trust gap short clips cannot hold (scaffold; they correct).",
      "Or name the topic in one plain sentence.",
    ],
    audience: [
      "People who already watched short tips but still do not trust judgment (scaffold).",
      "Prospects comparing options and needing depth (scaffold).",
      "Peers who need a clearer shared language (scaffold).",
      "Or name who it helps in their own words.",
    ],
    example: [
      "One anonymized practice beat from their work (scaffold; they fill facts).",
      "A before/after of a process they can show (scaffold; they fill facts).",
      "A decision story that proved their standpoint (scaffold; they fill facts).",
      "Or share one concrete example in their own words.",
    ],
    trustOutcome: [
      "They trust the speaker's judgment on this topic (scaffold).",
      "They can name the mechanism in their own words (scaffold).",
      "They feel ready to ask a soft next question (scaffold).",
      "Or name the trust outcome they want.",
    ],
    evidenceTypes: [
      "结果证据: one outcome they can show without inventing numbers.",
      "过程证据: one process step they can film.",
      "角色证据: why they are the right person to teach this.",
      "人品证据: a boundary or care habit they keep.",
    ],
    language: [
      "English only, spoken and filmable.",
      "Chinese only, spoken and filmable.",
      "Mixed: Chinese spoken with short English terms they already use.",
    ],
  },
  probeHints: [
    "信任证据清单",
    "信任复利公式",
    "信任引擎",
    "结果证据",
    "过程证据",
    "角色证据",
    "人品证据",
    "长视频",
    "先给价值",
    "内容资产",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.trust-evidence-checklist",
    "fw.trust-compound-formula",
    "fw.trust-engine",
    "cl.short-vs-long-video",
    "pr.exposure-trust-conversion",
    "cl.value-then-convert",
    "cl.content-not-ads",
    "pr.advice-vs-ego",
  ],
  starterPrompt:
    "Using my intake, outline a dense long trust-path video (5 to 15 minutes): place Trust Evidence types (结果/过程/角色/人品), frame as 看见你→理解你→相信你→问你→买你 where useful, and close with a soft next step. Structure for MY craft.",
  chatOpener:
    "Hey. I will help you outline a longer teach (5 to 15 minutes) that builds trust, not filler.\n\nHere is how we will work:\n- We collect criticals, then I confirm the plan before the full outline\n- You share topic, audience, example, trust outcome, and Trust Evidence types\n- You leave with a dense trust-path outline you can film\n\nWhat topic can you teach for 5 to 15 minutes without fluff?",
  chatOpenerZh:
    "我会帮你搭长视频信任大纲（5 到 15 分钟），不堆注水。\n\n我们这样配合：\n- 先收齐关键信息，确认计划后再写完整大纲\n- 你说题目、受众、例子、信任结果，以及信任证据类型\n- 你会带走能开拍的密实信任路径大纲\n\n有哪个题目你能讲 5 到 15 分钟还不注水？",
  systemOverlay: [
    "## Module mode: Long Video Trust Script (qualityRuntime Script/Spoken)",
    "You are running the Long Video Trust Script tool for this user.",
    "Job: denser teach outline (5 to 15 minutes) so viewers stay long enough to trust judgment. Do not shrink this into a 15 second ad or thin Reel.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first full outline unless they explicitly say just write it after criticals are filled.",
    "Bind Jeff frameworks: Trust Evidence Checklist / 信任证据清单 (`fw.trust-evidence-checklist`), 信任复利公式 (`fw.trust-compound-formula`), Trust Engine / 信任引擎 (`fw.trust-engine`).",
    "",
    "### Distinct job (not Reel OPENS / not S.T.O.R.Y only)",
    "Long video role is trust depth; short is exposure. Frame as a trust path, not stock YouTube boilerplate.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Get seen before trust before deal; standpoint; content assets not ads; advice vs ego; value then convert where relevant.",
    "ANTI-GENERIC: if it could come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: topic, audience, example, trust outcome, Trust Evidence types, language.",
    "Ask at most 1 to 2 questions per Collect turn. Prefer Jeff-shaped asks over a generic questionnaire.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent Jeff patient stories or fake metrics.",
    "User owns niche facts. Jeff owns craft (Trust Evidence placement, trust path shape).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full multi-section outline in Confirm.",
    "",
    "### Deliverable shape (dense; 5 to 15 minutes)",
    "Frame as a trust path, not stock YouTube boilerplate (no generic intro/hooks/outro theater).",
    "1. Open: why this matters for trust (align to Trust Engine when useful: 看见你 → 理解你 → 相信你 → 问你 → 买你).",
    "2. Teaching sections (3 to 5): speakable beats.",
    "3. Trust Evidence placement (required): label which sections prove 结果证据 / 过程证据 / 角色证据 / 人品证据. At least two types must appear; name gaps honestly.",
    "4. Example placement from the conversation (label as THEIR practice).",
    "5. Compound note (optional one line): 真实 × 执行 × 共鸣 when it fits their facts.",
    "6. Close: soft next step; value then light convert.",
    "7. End with named refine levers.",
    "Never invent Jeff patient stories as doctrine.",
    "Write the whole outline in the locked UI locale language.",
    "",
    "### Refine",
    "After a dense outline exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Hard bans",
    "No overnight-fame. Do not ship a generic YouTube template with Jeff labels glued on.",
    "Prefer fw.trust-evidence-checklist, fw.trust-compound-formula, fw.trust-engine, cl.short-vs-long-video, pr.exposure-trust-conversion, cl.value-then-convert, cl.content-not-ads, pr.advice-vs-ego when present.",
    "Sources only from probe / probe_jeff.",
  ].join("\n"),
};
