import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * Process Proof Reel: why customers choose us + how we work (advice vs ego).
 * Quality Runtime (Q2): Collect → Confirm → Deliver → Refine on script-spoken family.
 * Dense ~60s+ process proof; not a hard-sell ad and not a generic tip Reel.
 */
export const PROCESS_PROOF_REEL_PACK: ModulePack = {
  moduleId: "process-proof-reel",
  qualityRuntime: true,
  qualityFamily: "script-spoken",
  confirmBlurb:
    "Mirror the process-proof plan in 2 to 4 bullets: why people pick you, the filmable process step, viewer takeaway, soft CTA, language, and any assumptions. Ask for go-ahead before the full dense ~60s+ script.",
  deliverableSectionOrder: [
    "Hook (timed)",
    "How-we-work beat that teaches the viewer (timed)",
    "Soft close (timed)",
    "On-screen text cues",
    "Named refine levers",
  ],
  refineLevers: [
    "tighter Hook",
    "clearer process beat",
    "stronger viewer takeaway",
    "softer close",
  ],
  intakeFields: [
    {
      id: "whyChoose",
      label: "Why people pick you",
      placeholder: "The honest reason customers choose you",
      required: true,
      multiline: true,
    },
    {
      id: "processStep",
      label: "One process step you can show",
      placeholder: "A filmable step of how you work",
      required: true,
      multiline: true,
    },
    {
      id: "viewerTakeaway",
      label: "Viewer takeaway (even if they never buy)",
      placeholder: "What advice they leave with",
      required: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: true,
    },
    {
      id: "ctaSoftness",
      label: "CTA softness",
      placeholder: "Soft follow/save, or light invite",
      required: true,
    },
  ],
  qualitySlots: [
    {
      id: "whyChoose",
      label: "Why people pick you",
      criticality: "critical",
      probeHint: "The honest reason customers choose them, not a slogan.",
      placeholder: "The honest reason customers choose you",
      multiline: true,
      idkOptions: [
        "They show the work clearly, not only the result photo (scaffold; they correct).",
        "They explain decisions in plain words others skip (scaffold; they correct).",
        "They stay calm when the process gets messy (scaffold; they correct).",
        "Or name why people pick them in one plain sentence.",
      ],
    },
    {
      id: "processStep",
      label: "One process step you can show",
      criticality: "critical",
      probeHint: "One filmable step of how they work that teaches the viewer.",
      placeholder: "A filmable step of how you work",
      multiline: true,
      idkOptions: [
        "The first check they run before starting work (scaffold).",
        "One decision point clients usually get wrong (scaffold).",
        "A mid-process habit that protects quality (scaffold).",
        "Or describe one process step they can film this week.",
      ],
    },
    {
      id: "viewerTakeaway",
      label: "Viewer takeaway (even if they never buy)",
      criticality: "critical",
      probeHint: "What advice the viewer leaves with even if they never buy.",
      placeholder: "What advice they leave with",
      idkOptions: [
        "One check they can run on their own work (scaffold).",
        "A red flag to avoid in this niche (scaffold).",
        "A wording change that clarifies the next ask (scaffold).",
        "Or name the takeaway in their own words.",
      ],
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "critical",
      probeHint: "Match how they speak on camera: English, Chinese, or mixed.",
      placeholder: "English, Chinese, or mixed",
      idkOptions: [
        "English only, spoken and filmable.",
        "Chinese only, spoken and filmable.",
        "Mixed: Chinese spoken with short English terms they already use.",
      ],
    },
    {
      id: "ctaSoftness",
      label: "CTA softness",
      criticality: "critical",
      probeHint: "How soft should close be: follow/save or light invite?",
      placeholder: "Soft follow/save, or light invite",
      idkOptions: [
        "Soft: follow or save for the next process tip.",
        "Medium: DM a simple keyword for a checklist.",
        "Light invite: comment if they want the next step explained.",
      ],
    },
  ],
  idkOptionsBySlotId: {
    whyChoose: [
      "They show the work clearly, not only the result photo (scaffold; they correct).",
      "They explain decisions in plain words others skip (scaffold; they correct).",
      "They stay calm when the process gets messy (scaffold; they correct).",
      "Or name why people pick them in one plain sentence.",
    ],
    processStep: [
      "The first check they run before starting work (scaffold).",
      "One decision point clients usually get wrong (scaffold).",
      "A mid-process habit that protects quality (scaffold).",
      "Or describe one process step they can film this week.",
    ],
    viewerTakeaway: [
      "One check they can run on their own work (scaffold).",
      "A red flag to avoid in this niche (scaffold).",
      "A wording change that clarifies the next ask (scaffold).",
      "Or name the takeaway in their own words.",
    ],
    language: [
      "English only, spoken and filmable.",
      "Chinese only, spoken and filmable.",
      "Mixed: Chinese spoken with short English terms they already use.",
    ],
    ctaSoftness: [
      "Soft: follow or save for the next process tip.",
      "Medium: DM a simple keyword for a checklist.",
      "Light invite: comment if they want the next step explained.",
    ],
  },
  probeHints: [
    "advice vs ego",
    "process",
    "content asset",
    "not ads",
    "short video",
    "buy people",
    "过程证明",
    "信任",
    "内容资产",
    "不是广告",
    "probe_jeff",
  ],
  boundNodeIds: [
    "pr.advice-vs-ego",
    "cl.content-not-ads",
    "cl.buy-people-not-product",
    "cl.short-vs-long-video",
    "pr.exposure-trust-conversion",
  ],
  starterPrompt:
    "Using my intake, write a dense ~60s+ process-proof Reel: hook, how-we-work beat, soft close. Keep it advice-led, not ego flex.",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you write a dense process-proof Reel at about 60 seconds and above that shows how you work so trust can build.",
    firstAsk: "What is one process step you can honestly show on camera?",
    seed: "process-proof-reel",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你写一条密实过程证明 Reel，大约 60 秒及以上，让人看见你怎么做事，好建立信任。",
    firstAsk: "你能诚实上镜展示的一个流程步骤是什么？",
    seed: "process-proof-reel",
  }),
  systemOverlay: [
    "## Module mode: Process Proof Reel (qualityRuntime Script/Spoken)",
    "You are running the Process Proof Reel tool for this user.",
    "Job: produce a dense ~60s+ Reel that shows why customers choose them and how they work, as advice not ego.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first full script unless they explicitly say just write it after criticals are filled.",
    "",
    "### Distinct job (not value tip Reel / not hot take / not OPENS rewrite)",
    "Show craft. Teach the viewer through process. Soft close. Content asset, not hard-sell ad.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Advice vs ego: process proof serves the viewer. Buy people, not product theater.",
    "Content assets are not ads. Get seen → trust → deal framing when useful.",
    "ANTI-GENERIC: if it could come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: why people pick you, one process step, viewer takeaway, language, CTA softness.",
    "Ask at most 1 to 2 questions per Collect turn. Prefer Jeff-shaped asks over a generic business questionnaire.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent client names or private proof.",
    "User owns niche facts. Jeff owns craft (advice vs ego, soft close).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full timed script in Confirm.",
    "",
    "### Deliverable shape (dense; ~60s+)",
    "1. Hook (attention + why this process matters) + approximate seconds.",
    "2. How-we-work beat: show process; teach the viewer + approximate seconds.",
    "3. Soft close aligned with CTA softness + approximate seconds.",
    "4. On-screen text cues.",
    "5. End with named refine levers.",
    "Timing should read as about 60 seconds and above, not a thin 15 second flex clip.",
    "Ground every beat in their process facts. Different inputs must produce different scripts.",
    "Write the whole script in the locked UI locale language.",
    "",
    "### Refine",
    "After a dense script exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Hard bans",
    "No overnight-fame. Never invent Jeff niche case studies as doctrine.",
    "Prefer pr.advice-vs-ego, cl.content-not-ads, cl.buy-people-not-product, cl.short-vs-long-video, pr.exposure-trust-conversion when present.",
    "Sources only from probe / probe_jeff.",
  ].join("\n"),
};
