import type { ModulePack } from "@/lib/modules/types";

/**
 * Hook Formula (AUG-D2): opening lines for the first second of attention.
 * Module id kept as scroll-stop-hook.
 * Formula: 对象 ＋ 痛点 ＋ 反差/结果 ＋ 好奇.
 * Quality Runtime (Q4): Collect → Confirm → Deliver → Refine on hook-line family.
 * Chat path upgraded; Hook Studio batch chrome stays (Studio markers force Deliver).
 */
export const SCROLL_STOP_HOOK_PACK: ModulePack = {
  moduleId: "scroll-stop-hook",
  qualityRuntime: true,
  qualityFamily: "hook-line",
  confirmBlurb:
    "Mirror the open plan in 2 to 4 bullets: 对象, 痛点, 反差/结果, 好奇, plus any assumptions. Ask for go-ahead before the dense annotated opens. Do not write a full Reel script.",
  deliverableSectionOrder: [
    "5 to 8 opening lines",
    "Four-leg annotation under each (对象 / 痛点 / 反差或结果 / 好奇)",
    "Reject incomplete candidates with reason",
    "Optional avoid example",
    "Named refine levers",
  ],
  refineLevers: [
    "sharper 对象",
    "stronger 痛点",
    "clearer 反差/结果",
    "tighter 好奇",
    "which line to film first",
  ],
  intakeFields: [
    {
      id: "audience",
      label: "对象 (who)",
      placeholder: "Who this open speaks to",
      required: true,
    },
    {
      id: "pain",
      label: "痛点 (pain)",
      placeholder: "The pain that should stop the scroll",
      required: true,
      multiline: true,
    },
    {
      id: "contrast",
      label: "反差/结果 (contrast or result)",
      placeholder: "The contrast or result that snaps attention",
      required: true,
      multiline: true,
    },
    {
      id: "curiosity",
      label: "好奇 (curiosity)",
      placeholder: "What makes them need the next second",
      required: true,
    },
    {
      id: "topic",
      label: "Topic (optional context)",
      placeholder: "What this video is about in one line",
      required: false,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: false,
    },
  ],
  qualitySlots: [
    {
      id: "audience",
      label: "对象 (who)",
      criticality: "critical",
      probeHint: "Who this open speaks to in the first second.",
      placeholder: "Who this open speaks to",
      idkOptions: [
        "Newly diagnosed adults who feel overwhelmed (scaffold; they correct).",
        "Busy practitioners who scroll past fluff (scaffold; they correct).",
        "A named role stuck at one clear pain (scaffold; they name the role).",
        "Or name who this open is for in one plain sentence.",
      ],
    },
    {
      id: "pain",
      label: "痛点 (pain)",
      criticality: "critical",
      probeHint: "The pain that should stop the scroll in second one.",
      placeholder: "The pain that should stop the scroll",
      multiline: true,
      idkOptions: [
        "They keep trying generic tips and still feel stuck (scaffold; they reword).",
        "They fear being invisible even when they post (scaffold; they reword).",
        "They confuse effort with progress (scaffold; they reword).",
        "Or name the pain in their own words.",
      ],
    },
    {
      id: "contrast",
      label: "反差/结果 (contrast or result)",
      criticality: "critical",
      probeHint: "The contrast or result that snaps attention without overnight-fame claims.",
      placeholder: "The contrast or result that snaps attention",
      multiline: true,
      idkOptions: [
        "Small daily systems beat motivation speeches (scaffold; they reword).",
        "Seen first, then trusted, then invited (scaffold; they reword).",
        "Assets beat ads for the same tip (scaffold; they reword).",
        "Or name the contrast or result in their words.",
      ],
    },
    {
      id: "curiosity",
      label: "好奇 (curiosity)",
      criticality: "critical",
      probeHint: "What makes them need the next second without clickbait that breaks trust.",
      placeholder: "What makes them need the next second",
      idkOptions: [
        "The one mechanism most people skip (scaffold; they name it).",
        "What changed after they stopped chasing volume (scaffold; they reword).",
        "The question their buyer cannot ignore this week (scaffold; they reword).",
        "Or say what curiosity pull you want in one line.",
      ],
    },
    {
      id: "topic",
      label: "Topic (optional context)",
      criticality: "optional",
      probeHint: "Optional one-line topic so opens stay on the piece.",
      placeholder: "What this video is about in one line",
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "optional",
      probeHint: "Optional language preference for the opens.",
      placeholder: "English, Chinese, or mixed",
    },
  ],
  idkOptionsBySlotId: {
    audience: [
      "Newly diagnosed adults who feel overwhelmed (scaffold; they correct).",
      "Busy practitioners who scroll past fluff (scaffold; they correct).",
      "A named role stuck at one clear pain (scaffold; they name the role).",
      "Or name who this open is for in one plain sentence.",
    ],
    pain: [
      "They keep trying generic tips and still feel stuck (scaffold; they reword).",
      "They fear being invisible even when they post (scaffold; they reword).",
      "They confuse effort with progress (scaffold; they reword).",
      "Or name the pain in their own words.",
    ],
    contrast: [
      "Small daily systems beat motivation speeches (scaffold; they reword).",
      "Seen first, then trusted, then invited (scaffold; they reword).",
      "Assets beat ads for the same tip (scaffold; they reword).",
      "Or name the contrast or result in their words.",
    ],
    curiosity: [
      "The one mechanism most people skip (scaffold; they name it).",
      "What changed after they stopped chasing volume (scaffold; they reword).",
      "The question their buyer cannot ignore this week (scaffold; they reword).",
      "Or say what curiosity pull you want in one line.",
    ],
  },
  /** First four win the probe hint cap: formula legs only. */
  probeHints: [
    "对象",
    "痛点",
    "反差",
    "好奇",
    "Hook Formula",
    "钩子",
    "short video",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.hook-formula",
    "cl.short-vs-long-video",
    "pr.standpoint-or-invisible",
    "rj.overnight-fame",
    "pr.exposure-trust-conversion",
  ],
  starterPrompt:
    "Using my intake, apply Hook Formula (对象＋痛点＋反差/结果＋好奇): several opening lines for the first 1 to 3 seconds, each annotated with all four legs.",
  chatOpener:
    "Hey. I will help you write opening lines that stop the scroll in the first 1 to 3 seconds.\n\nHere is how we will work:\n- We collect the four Hook Formula legs, then I confirm before the dense annotated opens\n- You tell me who the video is for, and what pain should make them pause\n- You leave with stronger opens only, not a full Reel script\n\nWho is this video for, and what problem should hit them first?",
  chatOpenerZh:
    "我会帮你写前 1 到 3 秒能停住滑动的开场句。\n\n我们这样配合：\n- 先收齐 Hook Formula 四腿，确认后再给密实标注开场\n- 你告诉我视频是讲给谁听的，以及哪一个痛点该让他们停下来\n- 你会带走更强开场，不是整支 Reel 脚本\n\n这条视频是讲给谁听的？哪一个问题该先打到他们？",
  systemOverlay: [
    "## Module mode: Hook Formula (qualityRuntime Hook/Line)",
    "You are running the Hook Formula tool (catalog id scroll-stop-hook) for this user.",
    "Job: opening lines only for the first 1 to 3 seconds of attention. Not the full Reel body unless asked.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first annotated batch unless they explicitly say just write it after criticals are filled.",
    "Hook Studio batch Generate turns carry Studio markers and must deliver JSON cards immediately (lifecycle forces Deliver for those turns).",
    "",
    "### Named doctrine (AUG-D2, must teach)",
    "Hook Formula: 对象 ＋ 痛点 ＋ 反差/结果 ＋ 好奇.",
    "Every opening line MUST carry all four legs. Annotate each line with: 对象 / 痛点 / 反差或结果 / 好奇.",
    "Reject incomplete lines (missing any leg). Do not invent a different hook recipe.",
    "Bind fw.hook-formula.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: 对象, 痛点, 反差/结果, 好奇. Topic and language optional.",
    "Ask at most 1 to 2 questions per Collect turn. Prefer 对象 + 痛点 first if both empty.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent niche facts.",
    "User owns niche facts. Jeff owns craft (Hook Formula legs).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full annotated open batch in Confirm.",
    "",
    "### Deliverable shape (opens only; not a full script)",
    "1. 5 to 8 numbered opening lines.",
    "2. Under each line: annotate 对象 / 痛点 / 反差或结果 / 好奇 (all four required).",
    "3. Drop any candidate that cannot fill all four; say why it was rejected.",
    "4. Optional avoid example (viral-bait or ad-like).",
    "5. End with named refine levers (sharper 对象, stronger 痛点, clearer 反差/结果, tighter 好奇, film-first pick).",
    "Ground every line in their concrete answers. Different inputs must produce different opens.",
    "",
    "### Refine",
    "After a dense open batch exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Jeff pivots (must show)",
    "Hooks serve get-seen so trust can start. Standpoint can ride inside 反差 or 好奇. Reject overnight-fame / viral-as-guarantee.",
    "No hard pitch in second one.",
    "ANTI-GENERIC: ban clickbait that breaks trust. Each line needs a Jeff reason grounded in the four legs.",
    "",
    "### Hard bans",
    "Prefer fw.hook-formula, cl.short-vs-long-video, pr.standpoint-or-invisible, rj.overnight-fame, pr.exposure-trust-conversion.",
    "Thin hook craft KB: Generally → Jeff → steer; label practice drafts.",
    "Do not replace Hook Formula with GOAT, generic hook/body/close, or unbound scroll-stop tips.",
    "Do not turn this tool into a full IG Reel script writer.",
    "",
    "### After",
    "Which complete four-leg line do they film today?",
  ].join("\n"),
};
