import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * Hook Formula (AUG-D2): opening lines for the first second of attention.
 * Module id kept as scroll-stop-hook.
 * Formula: 对象 ＋ 痛点 ＋ 反差/结果 ＋ 好奇.
 * Quality Runtime (Q4): Collect → Confirm → Deliver → Refine on hook-line family.
 * Former Hook Studio batch prompt ideas live here as chat overlay reference only.
 */
export const SCROLL_STOP_HOOK_PACK: ModulePack = {
  moduleId: "scroll-stop-hook",
  qualityRuntime: true,
  qualityFamily: "hook-line",
  confirmBlurb:
    "Mirror the open plan in 2 to 4 bullets: 对象, 痛点, 反差/结果, 好奇, plus any assumptions. Ask for go-ahead before the dense annotated opens. Do not write a full Reel script.",
  deliverableSectionOrder: [
    "5 to 8 opening lines",
    "Four-leg annotation under each (对象 / 痛点 / 反差或结果 / 好奇)",
    "Reject incomplete candidates with reason",
    "Optional avoid example",
    "Named refine levers",
  ],
  refineLevers: [
    "sharper 对象",
    "stronger 痛点",
    "clearer 反差/结果",
    "tighter 好奇",
    "which line to film first",
  ],
  intakeFields: [
    {
      id: "audience",
      label: "对象 (who)",
      placeholder: "Who this open speaks to",
      required: true,
    },
    {
      id: "pain",
      label: "痛点 (pain)",
      placeholder: "The pain that should stop the scroll",
      required: true,
      multiline: true,
    },
    {
      id: "contrast",
      label: "反差/结果 (contrast or result)",
      placeholder: "The contrast or result that snaps attention",
      required: true,
      multiline: true,
    },
    {
      id: "curiosity",
      label: "好奇 (curiosity)",
      placeholder: "What makes them need the next second",
      required: true,
    },
    {
      id: "topic",
      label: "Topic (optional context)",
      placeholder: "What this video is about in one line",
      required: false,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: false,
    },
  ],
  qualitySlots: [
    {
      id: "audience",
      label: "对象 (who)",
      criticality: "critical",
      probeHint: "Who this open speaks to in the first second.",
      placeholder: "Who this open speaks to",
      idkOptions: [
        "Newly diagnosed adults who feel overwhelmed (scaffold; they correct).",
        "Busy practitioners who scroll past fluff (scaffold; they correct).",
        "A named role stuck at one clear pain (scaffold; they name the role).",
        "Or name who this open is for in one plain sentence.",
      ],
    },
    {
      id: "pain",
      label: "痛点 (pain)",
      criticality: "critical",
      probeHint: "The pain that should stop the scroll in second one.",
      placeholder: "The pain that should stop the scroll",
      multiline: true,
      idkOptions: [
        "They keep trying generic tips and still feel stuck (scaffold; they reword).",
        "They fear being invisible even when they post (scaffold; they reword).",
        "They confuse effort with progress (scaffold; they reword).",
        "Or name the pain in their own words.",
      ],
    },
    {
      id: "contrast",
      label: "反差/结果 (contrast or result)",
      criticality: "critical",
      probeHint: "The contrast or result that snaps attention without overnight-fame claims.",
      placeholder: "The contrast or result that snaps attention",
      multiline: true,
      idkOptions: [
        "Small daily systems beat motivation speeches (scaffold; they reword).",
        "Seen first, then trusted, then invited (scaffold; they reword).",
        "Assets beat ads for the same tip (scaffold; they reword).",
        "Or name the contrast or result in their words.",
      ],
    },
    {
      id: "curiosity",
      label: "好奇 (curiosity)",
      criticality: "critical",
      probeHint: "What makes them need the next second without clickbait that breaks trust.",
      placeholder: "What makes them need the next second",
      idkOptions: [
        "The one mechanism most people skip (scaffold; they name it).",
        "What changed after they stopped chasing volume (scaffold; they reword).",
        "The question their buyer cannot ignore this week (scaffold; they reword).",
        "Or say what curiosity pull you want in one line.",
      ],
    },
    {
      id: "topic",
      label: "Topic (optional context)",
      criticality: "optional",
      probeHint: "Optional one-line topic so opens stay on the piece.",
      placeholder: "What this video is about in one line",
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "optional",
      probeHint: "Optional language preference for the opens.",
      placeholder: "English, Chinese, or mixed",
    },
  ],
  idkOptionsBySlotId: {
    audience: [
      "Newly diagnosed adults who feel overwhelmed (scaffold; they correct).",
      "Busy practitioners who scroll past fluff (scaffold; they correct).",
      "A named role stuck at one clear pain (scaffold; they name the role).",
      "Or name who this open is for in one plain sentence.",
    ],
    pain: [
      "They keep trying generic tips and still feel stuck (scaffold; they reword).",
      "They fear being invisible even when they post (scaffold; they reword).",
      "They confuse effort with progress (scaffold; they reword).",
      "Or name the pain in their own words.",
    ],
    contrast: [
      "Small daily systems beat motivation speeches (scaffold; they reword).",
      "Seen first, then trusted, then invited (scaffold; they reword).",
      "Assets beat ads for the same tip (scaffold; they reword).",
      "Or name the contrast or result in their words.",
    ],
    curiosity: [
      "The one mechanism most people skip (scaffold; they name it).",
      "What changed after they stopped chasing volume (scaffold; they reword).",
      "The question their buyer cannot ignore this week (scaffold; they reword).",
      "Or say what curiosity pull you want in one line.",
    ],
  },
  /** First four win the probe hint cap: formula legs only. */
  probeHints: [
    "对象",
    "痛点",
    "反差",
    "好奇",
    "Hook Formula",
    "钩子",
    "short video",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.hook-formula",
    "cl.short-vs-long-video",
    "pr.standpoint-or-invisible",
    "rj.overnight-fame",
    "pr.exposure-trust-conversion",
  ],
  starterPrompt:
    "Using my intake, apply Hook Formula (对象＋痛点＋反差/结果＋好奇): several opening lines for the first 1 to 3 seconds, each annotated with all four legs.",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you write scroll-stop opens for the first 1 to 3 seconds.",
    firstAsk: "Who is this video for, and what problem should hit them first?",
    seed: "scroll-stop-hook",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你写前 1 到 3 秒能停住滑动的开场。",
    firstAsk: "这条视频是讲给谁听的，先打哪个痛点？",
    seed: "scroll-stop-hook",
  }),
  systemOverlay: [
    "## Module mode: Hook Formula (qualityRuntime Hook/Line)",
    "You are running the Hook Formula tool (catalog id scroll-stop-hook) for this user.",
    "Job: opening lines only for the first 1 to 3 seconds of attention. Not the full Reel body unless asked.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first annotated batch unless they explicitly say just write it after criticals are filled.",
    "Reply in markdown: each open is a ## heading (short label), then the spoken line, then bullets for 对象 / 痛点 / 反差或结果 / 好奇. Do not emit three separate \"1.\" items. Do not invent a second JSON card product UI.",
    "",
    "### Named doctrine (AUG-D2, must teach)",
    "Hook Formula: 对象 ＋ 痛点 ＋ 反差/结果 ＋ 好奇.",
    "Every opening line MUST carry all four legs. Annotate each line with: 对象 / 痛点 / 反差或结果 / 好奇.",
    "Reject incomplete lines (missing any leg). Do not invent a different hook recipe.",
    "Name while applying: Jeff's <<Hook Formula>> / Jeff 的 <<Hook Formula>> (`fw.hook-formula`). Apply; do not lecture.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: 对象, 痛点, 反差/结果, 好奇. Topic and language optional.",
    "Ask at most 1 to 2 questions per Collect turn. Prefer 对象 + 痛点 first if both empty.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent niche facts.",
    "User owns niche facts. Jeff owns craft (Hook Formula legs).",
    "When they already paste niche, proof, and a topic idea, treat that as filled legs and move toward Confirm or Deliver without re-asking what they already gave.",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full annotated open batch in Confirm.",
    "",
    "### Deliverable shape (opens only; not a full script)",
    "5 to 8 opens. For EACH open use this markdown shape:",
    "## Short label (who or angle)",
    "Spoken opening line.",
    "- 对象: ...",
    "- 痛点: ...",
    "- 反差/结果: ...",
    "- 好奇: ...",
    "Hash headings are required per open. Do not prefix every open with \"1.\". If you use a numbered list at all, it must be 1. 2. 3. contiguous in one list.",
    "Drop any candidate that cannot fill all four; say why it was rejected.",
    "Optional avoid example (viral-bait or ad-like).",
    "End with named refine levers (sharper 对象, stronger 痛点, clearer 反差/结果, tighter 好奇, film-first pick).",
    "Mark which line to film first when you deliver a batch.",
    "Ground every line in their concrete answers. Different inputs must produce different opens.",
    "",
    "### Alternate inputs (still chat Collect → Confirm → Deliver → Refine)",
    "Rewrite paste: if they paste a current open (or open + body topic), keep the body topic and rewrite opens only. Prefer Jeff's <<Hook Formula>> legs on each rewrite; say briefly what changed vs the pasted open.",
    "Competitor samples: if they paste competitor opens, study them as PATTERN samples only. Name the scroll-stop mechanism. Rewrite into THIS user's niche, proof, and standpoint. Ban wholesale copy of their wording. Ban go-viral-like-them.",
    "Repeat a hit: if they paste their own strong opens, keep the winning mechanism; vary angle, specificity, or proof detail. No near-duplicates of the paste. why_it_works (or brief reason) must name the kept mechanism and what you varied.",
    "",
    "### Refine",
    "After a dense open batch exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Jeff pivots (must show)",
    "Hooks serve get-seen so trust can start. Standpoint can ride inside 反差 or 好奇. Reject overnight-fame / viral-as-guarantee.",
    "No hard pitch in second one.",
    "ANTI-GENERIC: ban clickbait that breaks trust. Each line needs a Jeff reason grounded in the four legs.",
    "",
    "### Hard bans",
    "Ban overnight fame, guaranteed viral, Maria principle labels, and trust-breaking clickbait in any field or line.",
    "Prefer fw.hook-formula, cl.short-vs-long-video, pr.standpoint-or-invisible, rj.overnight-fame, pr.exposure-trust-conversion.",
    "Thin hook craft KB: Generally → Jeff → steer; label practice drafts.",
    "Do not replace Hook Formula with GOAT, generic hook/body/close, or unbound scroll-stop tips.",
    "Do not turn this tool into a full IG Reel script writer.",
    "",
    "### After",
    "Which complete four-leg line do they film today?",
  ].join("\n"),
};
