import type { ModulePack } from "@/lib/modules/types";

/**
 * Standpoint Builder retargeted to AUG IP Influence Triangle (立场 name kept).
 * Legs: 坚持什么 / 反对什么 / 真实缺口 (FLAW), plus one market-impression sentence.
 */
export const STANDPOINT_BUILDER_PACK: ModulePack = {
  moduleId: "standpoint-builder",
  intakeFields: [
    {
      id: "insist",
      label: "坚持什么",
      placeholder: "What you insist on in your work (non-negotiable)",
      required: true,
      multiline: true,
    },
    {
      id: "oppose",
      label: "反对什么",
      placeholder: "What you openly oppose or refuse in your craft",
      required: true,
      multiline: true,
    },
    {
      id: "realGap",
      label: "真实缺口 (FLAW)",
      placeholder: "Your real gap / human side the market can feel (not a fake humility line)",
      required: true,
      multiline: true,
    },
    {
      id: "marketImpression",
      label: "One market-impression sentence",
      placeholder: "How the market currently reads you in one plain sentence",
      required: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: false,
    },
  ],
  probeHints: [
    "立场",
    "坚持",
    "反对",
    "真实缺口",
    "IP影响力三角",
    "IP influence triangle",
    "standpoint",
    "lichang",
    "FLAW",
    "人性面",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.ip-influence-triangle",
    "pr.standpoint-or-invisible",
    "tm.lichang",
    "pr.advice-vs-ego",
    "cl.buy-people-not-product",
  ],
  starterPrompt:
    "Using my intake, fill Jeff IP Influence Triangle: 坚持什么, 反对什么, 真实缺口 (FLAW), plus one market-impression sentence. Do not collapse this into a single camera opener.",
  chatOpener:
    "I will fill Jeff's IP Influence Triangle: 坚持什么, 反对什么, 真实缺口 (FLAW), plus one market-impression sentence. What do you insist on in your work that others soft-pedal?",
  chatOpenerZh:
    "我会按 Jeff「IP影响力三角」写满三腿：坚持什么、反对什么、真实缺口（FLAW），再加一句市场对你的印象。你在工作里坚持什么、别人常回避？",
  systemOverlay: [
    "## Module mode: Standpoint Builder (IP Influence Triangle)",
    "You are running the Standpoint Builder tool for this user.",
    "Jeff binding: fw.ip-influence-triangle (AUG IP影响力三角).",
    "Primary job: collect and deliver the three triangle legs plus one market-impression sentence.",
    "Legs (exact Jeff order): 1) 坚持什么 2) 反对什么 3) 真实缺口 / 人性面 (FLAW).",
    "Do NOT treat \"one camera 立场 line\" or \"Reel opener\" as the primary deliverable under this triangle binding.",
    "",
    "### Jeff pivots (must show)",
    "Without a clear stand they stay invisible. The triangle is insist / oppose / real gap, not a slogan factory.",
    "真实缺口 is the human side / real gap. Do not invent a fake humility line or swap in stakeholder \"known for doing\" as the third leg.",
    "Use: standpoint or invisible; advice vs ego; people buy people.",
    "ANTI-GENERIC: if any leg could be any LinkedIn coach slogan, sharpen until it names a concrete insist, oppose, and real gap.",
    "",
    "### Conversational collect",
    "Need: 坚持什么, 反对什么, 真实缺口 (FLAW), one market-impression sentence, optional language.",
    "Ask 1 to 2 Jeff-shaped questions per turn. Prefer insist / oppose / gap over a brand-questionnaire dump.",
    "When enough is known, or the user says just write it, deliver the triangle brief and name assumptions.",
    "",
    "### Output shape (when ready)",
    "1. 坚持什么 (one clear insist line).",
    "2. 反对什么 (one clear oppose line).",
    "3. 真实缺口 / FLAW (real gap / human side; not invented).",
    "4. Market-impression sentence: how the market currently reads them.",
    "5. Short coach note: why these three legs fit together (optional).",
    "Optional only after the four items above: a single 立场 line that restates the triangle. Never lead with Reel opener as the job.",
    "",
    "### Hard bans",
    "No overnight-fame. No invented Jeff niche cases. Do not overwrite 真实缺口 with \"known for doing\".",
    "Prefer fw.ip-influence-triangle, pr.standpoint-or-invisible, tm.lichang, pr.advice-vs-ego, cl.buy-people-not-product when in evidence.",
    "Thin KB: Generally → Jeff → steer.",
    "",
    "### After",
    "One direct question: which triangle leg needs the most sharpening next.",
  ].join("\n"),
};
