import type { ModulePack } from "@/lib/modules/types";

/**
 * Story Trust Script: S.T.O.R.Y Founder Story (fw.story-founder-story).
 * Stories illustrate; do not invent Jeff case studies as doctrine.
 * Longer Problem→Search arcs belong in story-structure-search.
 */
export const STORY_TRUST_SCRIPT_PACK: ModulePack = {
  moduleId: "story-trust-script",
  intakeFields: [
    {
      id: "situation",
      label: "Situation / 起点处境",
      placeholder: "Where you or the client started (facts only)",
      required: true,
      multiline: true,
    },
    {
      id: "turningPoint",
      label: "Turning Point / 最大冲突",
      placeholder: "The conflict that forced a change",
      required: true,
      multiline: true,
    },
    {
      id: "obstacle",
      label: "Obstacle / 困难选择",
      placeholder: "The hard choice or cost",
      required: true,
      multiline: true,
    },
    {
      id: "reason",
      label: "Reason / 你坚持什么",
      placeholder: "What you refused to abandon",
      required: true,
      multiline: true,
    },
    {
      id: "yield",
      label: "Yield / 你要影响谁",
      placeholder: "Who this story is meant to move",
      required: true,
    },
    {
      id: "private",
      label: "What stays private",
      placeholder: "Names, details, or medical facts to omit",
      required: false,
      multiline: true,
    },
    {
      id: "format",
      label: "Format",
      placeholder: "Reel, long video, caption story…",
      required: false,
    },
  ],
  probeHints: [
    "S.T.O.R.Y",
    "创始人故事",
    "起点处境",
    "最大冲突",
    "困难选择",
    "你坚持什么",
    "你要影响谁",
    "story structure",
    "信任",
    "立场",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.story-founder-story",
    "fw.story-structure-search",
    "pr.exposure-trust-conversion",
    "pr.standpoint-or-invisible",
    "pr.advice-vs-ego",
    "cl.content-not-ads",
  ],
  starterPrompt:
    "Using my intake, write an S.T.O.R.Y trust script (Situation, Turning Point, Obstacle, Reason, Yield) using only MY story facts. Illustrative for MY practice; do not invent Jeff case studies.",
  chatOpener:
    "I will shape your story with S.T.O.R.Y (Situation / Turning Point / Obstacle / Reason / Yield), using your facts only. What was the starting situation?",
  chatOpenerZh:
    "我会用 S.T.O.R.Y（起点处境 / 最大冲突 / 困难选择 / 你坚持什么 / 你要影响谁）写你的故事信任脚本，只用你的事实。起点处境是什么？",
  systemOverlay: [
    "## Module mode: Story Trust Script (S.T.O.R.Y)",
    "You are running the Story Trust Script tool for this user.",
    "Exact Jeff framework: S.T.O.R.Y Founder Story (`fw.story-founder-story`).",
    "Job: turn their personal or client story into a trust-path script, not a resume.",
    "Steps (use these names; do not invent Setup / Turn / Belief land):",
    "1. Situation 起点处境",
    "2. Turning Point 最大冲突",
    "3. Obstacle 困难选择",
    "4. Reason 你坚持什么",
    "5. Yield 你要影响谁",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks over a generic business questionnaire.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "Deliver the script labeled S.T.O.R.Y:",
    "1. Situation: fill with THEIR facts only.",
    "2. Turning Point: fill with THEIR facts only.",
    "3. Obstacle: fill with THEIR facts only.",
    "4. Reason: fill with THEIR facts only.",
    "5. Yield: fill with THEIR facts only (who they want to influence).",
    "6. Optional soft close after Yield if format needs it.",
    "Every step must quote or paraphrase a user-supplied fact. If a step is missing, ask before inventing.",
    "Respect what stays private from what they told you in chat.",
    "",
    "### Longer story fork (hard)",
    "If the story needs Problem → Search → Story → Solution → What next, or they want a longer arc than S.T.O.R.Y fits, clearly offer the Story Structure (Problem to Search) tool (`fw.story-structure-search` / module `story-structure-search`) instead of inventing a hybrid.",
    "Do not invent Setup / Turn / Belief land as Jeff structure.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume; value then convert where relevant.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Bind to `fw.story-founder-story`. Stories illustrate. Never invent Jeff patient scripts, clinic anecdotes, or workshop case studies as Jeff teaching.",
    "Label the output as structure for THEIR story. Advice not ego. No overnight-fame.",
    "",
    "### Evidence binding",
    "Prefer: fw.story-founder-story, fw.story-structure-search, pr.exposure-trust-conversion, pr.standpoint-or-invisible, pr.advice-vs-ego, cl.content-not-ads when in the pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the script",
    "End with one direct question about which detail they will keep private on camera.",
  ].join("\n"),
};
