import type { ModulePack } from "@/lib/modules/types";

/**
 * Story Structure (Problem to Search): stakeholder Framework Needed PDF tool.
 * Elevated draft doctrine; not approved.
 * Quality Runtime (Q2 extra): clear Script/Spoken pack (longer story arc).
 * Collect → Confirm → Deliver → Refine. Dense spoken outline; not a thin teaser.
 */
export const STORY_STRUCTURE_SEARCH_PACK: ModulePack = {
  moduleId: "story-structure-search",
  qualityRuntime: true,
  qualityFamily: "script-spoken",
  confirmBlurb:
    "Mirror the Problem→Search plan in 2 to 4 bullets: Problem, Search, Solution, What next, language, and any assumptions. Ask for go-ahead before the full dense five-beat story outline.",
  deliverableSectionOrder: [
    "Problem",
    "Search (why it creates the story)",
    "Story beats",
    "Solution",
    "What next",
    "Named refine levers",
  ],
  refineLevers: [
    "sharper Problem",
    "richer Search",
    "clearer Story beats",
    "stronger Solution",
    "clearer What next",
  ],
  intakeFields: [
    {
      id: "problem",
      label: "Problem",
      placeholder: "The real problem at the start",
      required: true,
      multiline: true,
    },
    {
      id: "search",
      label: "Search",
      placeholder: "What you tried or hunted for",
      required: true,
      multiline: true,
    },
    {
      id: "solution",
      label: "Solution",
      placeholder: "What worked",
      required: true,
      multiline: true,
    },
    {
      id: "whatNext",
      label: "What next",
      placeholder: "One next step for the viewer",
      required: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: true,
    },
  ],
  qualitySlots: [
    {
      id: "problem",
      label: "Problem",
      criticality: "critical",
      probeHint: "The real problem that opens the story.",
      placeholder: "The real problem at the start",
      multiline: true,
      idkOptions: [
        "A stuck point their audience already feels (scaffold; they fill facts).",
        "A failed first approach that looked reasonable (scaffold; they fill facts).",
        "A gap between knowing tips and living them (scaffold; they fill facts).",
        "Or name the opening problem in their own words.",
      ],
    },
    {
      id: "search",
      label: "Search",
      criticality: "critical",
      probeHint: "What they tried or hunted for. Search creates the story.",
      placeholder: "What you tried or hunted for",
      multiline: true,
      idkOptions: [
        "Wrong advice they followed before the turn (scaffold; they fill facts).",
        "Options they compared and why each failed (scaffold; they fill facts).",
        "A hunt for a method that matched their constraints (scaffold; they fill facts).",
        "Or describe the search in their own words.",
      ],
    },
    {
      id: "solution",
      label: "Solution",
      criticality: "critical",
      probeHint: "What worked, grounded in their facts.",
      placeholder: "What worked",
      multiline: true,
      idkOptions: [
        "The practice that finally stuck (scaffold; they fill facts).",
        "The standpoint shift that changed the work (scaffold; they fill facts).",
        "The simple system that replaced noise (scaffold; they fill facts).",
        "Or name what worked in their own words.",
      ],
    },
    {
      id: "whatNext",
      label: "What next",
      criticality: "critical",
      probeHint: "One next step for the viewer after the solution.",
      placeholder: "One next step for the viewer",
      idkOptions: [
        "Soft: try one practice for seven days.",
        "Save or follow for the next beat in the series.",
        "Light invite: reply with their stuck point.",
        "Or name the viewer next step.",
      ],
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "critical",
      probeHint: "Match how they speak on camera: English, Chinese, or mixed.",
      placeholder: "English, Chinese, or mixed",
      idkOptions: [
        "English only, spoken and filmable.",
        "Chinese only, spoken and filmable.",
        "Mixed: Chinese spoken with short English terms they already use.",
      ],
    },
  ],
  idkOptionsBySlotId: {
    problem: [
      "A stuck point their audience already feels (scaffold; they fill facts).",
      "A failed first approach that looked reasonable (scaffold; they fill facts).",
      "A gap between knowing tips and living them (scaffold; they fill facts).",
      "Or name the opening problem in their own words.",
    ],
    search: [
      "Wrong advice they followed before the turn (scaffold; they fill facts).",
      "Options they compared and why each failed (scaffold; they fill facts).",
      "A hunt for a method that matched their constraints (scaffold; they fill facts).",
      "Or describe the search in their own words.",
    ],
    solution: [
      "The practice that finally stuck (scaffold; they fill facts).",
      "The standpoint shift that changed the work (scaffold; they fill facts).",
      "The simple system that replaced noise (scaffold; they fill facts).",
      "Or name what worked in their own words.",
    ],
    whatNext: [
      "Soft: try one practice for seven days.",
      "Save or follow for the next beat in the series.",
      "Light invite: reply with their stuck point.",
      "Or name the viewer next step.",
    ],
    language: [
      "English only, spoken and filmable.",
      "Chinese only, spoken and filmable.",
      "Mixed: Chinese spoken with short English terms they already use.",
    ],
  },
  probeHints: [
    "story structure",
    "problem search story",
    "founder story",
    "what next",
    "故事结构",
    "寻找",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.story-structure-search",
    "fw.story-founder-story",
    "fw.opens-60s-five-act",
  ],
  starterPrompt:
    "Using my intake, run Story Structure (Problem to Search) and deliver a dense five-beat spoken outline for this Jeff tool.",
  chatOpener:
    "I'll help you build a dense longer story structure: Problem, Search, Story, Solution, What next. What problem opens the story?",
  chatOpenerZh:
    "我来帮你搭密实更长的故事结构：问题、寻找、故事、解法、下一步。打开故事的问题是什么？",
  systemOverlay: [
    "## Module mode: Story Structure (Problem to Search) (qualityRuntime Script/Spoken)",
    "You are running the Story Structure (Problem to Search) tool (catalog id story-structure-search) for this user.",
    "Job: Longer dense story arc: Problem, Search, Story, Solution, What next. Search creates the story.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first full outline unless they explicitly say just write it after criticals are filled.",
    "",
    "### Distinct job (not S.T.O.R.Y Founder Story / not OPENS Reel)",
    "Use Problem → Search → Story → Solution → What next. Reminder: without search, a story is just something that happened.",
    "If they need Situation / Turning Point / Obstacle / Reason / Yield, offer `story-trust-script` instead of inventing a hybrid.",
    "Labels like Suggested/draft are not confirmed IP.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume.",
    "ANTI-GENERIC: if it could come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: Problem, Search, Solution, What next, language.",
    "Ask at most 1 to 2 questions per Collect turn.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent story facts or Jeff case studies.",
    "User owns niche facts. Jeff owns craft (Problem→Search structure).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full five-beat outline in Confirm.",
    "",
    "### Deliverable shape (dense spoken outline)",
    "1. Problem.",
    "2. Search (why it creates the story).",
    "3. Story beats.",
    "4. Solution.",
    "5. What next.",
    "6. Reminder: without search, a story is just something that happened.",
    "7. End with named refine levers.",
    "Density is job-shaped: full arc, not a thin teaser. Different inputs must produce different outlines.",
    "Write the whole outline in the locked UI locale language.",
    "",
    "### Refine",
    "After a dense outline exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Hard bans",
    "Name while applying: Jeff's <<Story Structure (Problem to Search)>> / Jeff 的 <<Story Structure (Problem to Search)>> (`fw.story-structure-search`). Apply; do not lecture.",
    "Never invent Jeff niche case studies as doctrine. No overnight-fame.",
    "Prefer boundNodeIds when in the evidence pack. Sources only from probe / probe_jeff.",
  ].join("\n"),
};
