import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * Story Trust Script: S.T.O.R.Y Founder Story (fw.story-founder-story).
 * Stories illustrate; do not invent Jeff case studies as doctrine.
 * Longer Problem→Search arcs belong in story-structure-search.
 * Quality Runtime (Q2): Collect → Confirm → Deliver → Refine on script-spoken family.
 * Dense spoken S.T.O.R.Y; do not shrink into a 15s ad.
 */
export const STORY_TRUST_SCRIPT_PACK: ModulePack = {
  moduleId: "story-trust-script",
  qualityRuntime: true,
  qualityFamily: "script-spoken",
  confirmBlurb:
    "Mirror the S.T.O.R.Y plan in 2 to 4 bullets: Situation, Turning Point, Obstacle, Reason, Yield, what stays private, format, and any assumptions. Ask for go-ahead before the full dense trust script.",
  deliverableSectionOrder: [
    "Situation 起点处境",
    "Turning Point 最大冲突",
    "Obstacle 困难选择",
    "Reason 你坚持什么",
    "Yield 你要影响谁",
    "Optional soft close",
    "Named refine levers",
  ],
  refineLevers: [
    "sharper Situation",
    "clearer Turning Point",
    "stronger Obstacle cost",
    "firmer Reason",
    "clearer Yield",
  ],
  intakeFields: [
    {
      id: "situation",
      label: "Situation / 起点处境",
      placeholder: "Where you or the client started (facts only)",
      required: true,
      multiline: true,
    },
    {
      id: "turningPoint",
      label: "Turning Point / 最大冲突",
      placeholder: "The conflict that forced a change",
      required: true,
      multiline: true,
    },
    {
      id: "obstacle",
      label: "Obstacle / 困难选择",
      placeholder: "The hard choice or cost",
      required: true,
      multiline: true,
    },
    {
      id: "reason",
      label: "Reason / 你坚持什么",
      placeholder: "What you refused to abandon",
      required: true,
      multiline: true,
    },
    {
      id: "yield",
      label: "Yield / 你要影响谁",
      placeholder: "Who this story is meant to move",
      required: true,
    },
    {
      id: "private",
      label: "What stays private",
      placeholder: "Names, details, or medical facts to omit",
      required: false,
      multiline: true,
    },
    {
      id: "format",
      label: "Format",
      placeholder: "Reel, long video, caption story…",
      required: false,
    },
  ],
  qualitySlots: [
    {
      id: "situation",
      label: "Situation / 起点处境",
      criticality: "critical",
      probeHint: "Where they or the client started. Facts only.",
      placeholder: "Where you or the client started (facts only)",
      multiline: true,
      idkOptions: [
        "A plain starting place before the change (scaffold; they fill facts).",
        "A stuck routine that looked fine from outside (scaffold; they fill facts).",
        "A role or stage before the conflict arrived (scaffold; they fill facts).",
        "Or describe the starting situation in their own words.",
      ],
    },
    {
      id: "turningPoint",
      label: "Turning Point / 最大冲突",
      criticality: "critical",
      probeHint: "The conflict that forced a change.",
      placeholder: "The conflict that forced a change",
      multiline: true,
      idkOptions: [
        "A moment when the old way clearly failed (scaffold; they fill facts).",
        "A conflict that made staying the same costly (scaffold; they fill facts).",
        "A feedback or result they could not ignore (scaffold; they fill facts).",
        "Or name the turning point in their own words.",
      ],
    },
    {
      id: "obstacle",
      label: "Obstacle / 困难选择",
      criticality: "critical",
      probeHint: "The hard choice or cost they faced.",
      placeholder: "The hard choice or cost",
      multiline: true,
      idkOptions: [
        "A tradeoff between speed and integrity (scaffold; they fill facts).",
        "A cost they paid to keep the right practice (scaffold; they fill facts).",
        "A choice between looking good and telling the truth (scaffold; they fill facts).",
        "Or name the hard choice in their own words.",
      ],
    },
    {
      id: "reason",
      label: "Reason / 你坚持什么",
      criticality: "critical",
      probeHint: "What they refused to abandon.",
      placeholder: "What you refused to abandon",
      multiline: true,
      idkOptions: [
        "A standpoint they would still defend (scaffold; they reword).",
        "A practice that protects the people they serve (scaffold; they reword).",
        "A line they will not cross for easy attention (scaffold; they reword).",
        "Or say what they refused to abandon.",
      ],
    },
    {
      id: "yield",
      label: "Yield / 你要影响谁",
      criticality: "critical",
      probeHint: "Who this story is meant to move.",
      placeholder: "Who this story is meant to move",
      idkOptions: [
        "People stuck where they started (scaffold; they correct).",
        "Peers who need lived proof, not tips only (scaffold; they correct).",
        "Prospects who need to trust judgment before a deal (scaffold; they correct).",
        "Or name who they want to influence.",
      ],
    },
    {
      id: "private",
      label: "What stays private",
      criticality: "optional",
      probeHint: "Names, details, or medical facts to omit on camera.",
      placeholder: "Names, details, or medical facts to omit",
      multiline: true,
      idkOptions: [
        "Keep all names private; use role labels only.",
        "Omit medical numbers and clinic identifiers.",
        "Keep family details private; keep the mechanism.",
      ],
    },
    {
      id: "format",
      label: "Format",
      criticality: "optional",
      probeHint: "Reel, long video, or caption story.",
      placeholder: "Reel, long video, caption story…",
      idkOptions: [
        "Reel: denser spoken beats, still full S.T.O.R.Y.",
        "Long video: more room on Obstacle and Reason.",
        "Caption story: shorter lines, same five steps.",
      ],
    },
  ],
  idkOptionsBySlotId: {
    situation: [
      "A plain starting place before the change (scaffold; they fill facts).",
      "A stuck routine that looked fine from outside (scaffold; they fill facts).",
      "A role or stage before the conflict arrived (scaffold; they fill facts).",
      "Or describe the starting situation in their own words.",
    ],
    turningPoint: [
      "A moment when the old way clearly failed (scaffold; they fill facts).",
      "A conflict that made staying the same costly (scaffold; they fill facts).",
      "A feedback or result they could not ignore (scaffold; they fill facts).",
      "Or name the turning point in their own words.",
    ],
    obstacle: [
      "A tradeoff between speed and integrity (scaffold; they fill facts).",
      "A cost they paid to keep the right practice (scaffold; they fill facts).",
      "A choice between looking good and telling the truth (scaffold; they fill facts).",
      "Or name the hard choice in their own words.",
    ],
    reason: [
      "A standpoint they would still defend (scaffold; they reword).",
      "A practice that protects the people they serve (scaffold; they reword).",
      "A line they will not cross for easy attention (scaffold; they reword).",
      "Or say what they refused to abandon.",
    ],
    yield: [
      "People stuck where they started (scaffold; they correct).",
      "Peers who need lived proof, not tips only (scaffold; they correct).",
      "Prospects who need to trust judgment before a deal (scaffold; they correct).",
      "Or name who they want to influence.",
    ],
  },
  probeHints: [
    "S.T.O.R.Y",
    "创始人故事",
    "起点处境",
    "最大冲突",
    "困难选择",
    "你坚持什么",
    "你要影响谁",
    "story structure",
    "信任",
    "立场",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.story-founder-story",
    "fw.story-structure-search",
    "pr.exposure-trust-conversion",
    "pr.standpoint-or-invisible",
    "pr.advice-vs-ego",
    "cl.content-not-ads",
  ],
  starterPrompt:
    "Using my intake, write a dense S.T.O.R.Y trust script (Situation, Turning Point, Obstacle, Reason, Yield) using only MY story facts. Illustrative for MY practice; do not invent Jeff case studies.",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you shape a dense story that builds trust, using your facts only.",
    firstAsk: "What was the starting situation?",
    seed: "story-trust-script",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你把故事写成密实、能建立信任的脚本，只用你的事实。",
    firstAsk: "起点处境是什么？",
    seed: "story-trust-script",
  }),
  systemOverlay: [
    "## Module mode: Story Trust Script (S.T.O.R.Y) (qualityRuntime Script/Spoken)",
    "You are running the Story Trust Script tool for this user.",
    "Name while applying: Jeff's <<S.T.O.R.Y Founder Story>> / Jeff 的 <<S.T.O.R.Y Founder Story>> (`fw.story-founder-story`). Apply; do not lecture.",
    "Job: turn their personal or client story into a dense trust-path script, not a resume and not a 15 second ad.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first full script unless they explicitly say just write it after criticals are filled.",
    "Steps (use these names; do not invent Setup / Turn / Belief land):",
    "1. Situation 起点处境",
    "2. Turning Point 最大冲突",
    "3. Obstacle 困难选择",
    "4. Reason 你坚持什么",
    "5. Yield 你要影响谁",
    "",
    "### Distinct job (not OPENS Reel / not Problem→Search hybrid)",
    "If the story needs Problem → Search → Story → Solution → What next, or they want a longer arc than S.T.O.R.Y fits, clearly offer the Story Structure (Problem to Search) tool (`story-structure-search`) instead of inventing a hybrid.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Get seen before trust before deal; standpoint; content assets not ads; advice vs ego.",
    "ANTI-GENERIC: if it could come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: Situation, Turning Point, Obstacle, Reason, Yield.",
    "Optional: what stays private, format.",
    "Ask at most 1 to 2 questions per Collect turn. Prefer Jeff-shaped asks over a generic questionnaire.",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent story facts, patient names, or Jeff clinic anecdotes.",
    "Every step must quote or paraphrase a user-supplied fact. If a step is missing, ask before inventing.",
    "User owns story facts. Jeff owns craft (S.T.O.R.Y structure).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full S.T.O.R.Y script in Confirm.",
    "",
    "### Deliverable shape (dense spoken)",
    "Deliver the script labeled S.T.O.R.Y with speakable lines per step:",
    "1. Situation: THEIR facts only.",
    "2. Turning Point: THEIR facts only.",
    "3. Obstacle: THEIR facts only.",
    "4. Reason: THEIR facts only.",
    "5. Yield: THEIR facts only (who they want to influence).",
    "6. Optional soft close after Yield if format needs it.",
    "7. End with named refine levers.",
    "Respect what stays private. Density is job-shaped: full trust path, not a thin teaser.",
    "Write the whole script in the locked UI locale language.",
    "",
    "### Refine",
    "After a dense script exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Hard bans",
    "Stories illustrate. Never invent Jeff patient scripts, clinic anecdotes, or workshop case studies as Jeff teaching.",
    "Label the output as structure for THEIR story. Advice not ego. No overnight-fame.",
    "Prefer fw.story-founder-story, fw.story-structure-search, pr.exposure-trust-conversion, pr.standpoint-or-invisible, pr.advice-vs-ego, cl.content-not-ads when present.",
    "Sources only from probe / probe_jeff.",
  ].join("\n"),
};
