import type { ModulePack } from "@/lib/modules/types";

/**
 * Value → Convert Ladder: free value into a natural invite.
 */
export const VALUE_CONVERT_LADDER_PACK: ModulePack = {
  moduleId: "value-convert-ladder",
  intakeFields: [
    {
      id: "freeTeach",
      label: "What you teach for free",
      placeholder: "Tips, frameworks, stories you already share",
      required: true,
      multiline: true,
    },
    {
      id: "sell",
      label: "What you sell",
      placeholder: "Offer, service, product, or booking",
      required: true,
    },
    {
      id: "dropOff",
      label: "Where people drop off",
      placeholder: "Liked the tip but not ready to talk: where it breaks",
      required: true,
      multiline: true,
    },
    {
      id: "audience",
      label: "Audience",
      placeholder: "Who this ladder is for",
      required: false,
    },
  ],
  probeHints: [
    "value then convert",
    "content asset",
    "not ads",
    "trust",
    "invite",
    "exposure trust conversion",
    "先给价值再转化",
    "成交",
    "信任",
    "内容资产",
    "不是广告",
    "probe_jeff",
  ],
  boundNodeIds: [
    "cl.value-then-convert",
    "cl.content-not-ads",
    "pr.exposure-trust-conversion",
    "tm.content-asset",
  ],
  starterPrompt:
    "Using my intake, map a short ladder from free value to a natural invite, with asset types and coach-like language (not funnel theater).",
  chatOpener:
    "I will map a short ladder from free value to a natural invite (KB is thin on funnels; stay on nearest Jeff nodes). What do you teach for free, and what do you sell?",
  systemOverlay: [
    "## Module mode: Value → Convert Ladder",
    "You are running the Value → Convert Ladder tool for this user.",
    "Job: map how free value leads into a natural invite so convert content does not appear out of nowhere.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks over a generic business questionnaire.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "Deliver a short ladder:",
    "1. Rungs: 3 to 5 asset types from open value → trust deepen → light invite (label each).",
    "2. Sample language per rung: coach-like, not funnel-y.",
    "3. Drop-off fix: one concrete change aimed at their stated gap.",
    "4. Reminder: convert after value; do not hard-pitch in the first value asset.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume; value then convert where relevant.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Lead with open valuable content; convert after trust/value. Do not hoard expertise.",
    "Content assets are not ads. No overnight-fame promises.",
    "Never invent Jeff niche case studies or full offer architecture as confirmed doctrine (KB thin on epic pitch).",
    "If KB is thin: Generally → Jeff → steer to value-then-convert / content-not-ads.",
    "",
    "### Evidence binding",
    "Prefer: cl.value-then-convert, cl.content-not-ads, pr.exposure-trust-conversion, tm.content-asset when in the evidence pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the ladder",
    "End with one direct question that picks which rung they film next.",
  ].join("\n"),
};
