import type { ModulePack } from "@/lib/modules/types";
import {
  buildLifecycleOpener,
  buildLifecycleOpenerZh,
} from "@/lib/modules/qualityRuntime/familyOverlay";

/**
 * Value Teaching Reel: teach one tip openly; light next step.
 * Quality Runtime (Q2): Collect → Confirm → Deliver → Refine on script-spoken family.
 * Dense ~60s+ teach; not a thin tip clip and not a hard-sell ad.
 */
export const VALUE_TEACHING_REEL_PACK: ModulePack = {
  moduleId: "value-teaching-reel",
  qualityRuntime: true,
  qualityFamily: "script-spoken",
  confirmBlurb:
    "Mirror the value Reel plan in 2 to 4 bullets: the one tip, who it helps, soft next step, language, and any assumptions. Ask for go-ahead before the full dense ~60s+ script.",
  deliverableSectionOrder: [
    "Hook that promises the tip (timed)",
    "Teaching beat with speakable steps (timed)",
    "Light invite / soft next step (timed)",
    "Optional on-screen text",
    "Named refine levers",
  ],
  refineLevers: [
    "tighter Hook",
    "clearer teaching steps",
    "softer next step",
    "tighter on-screen text",
  ],
  intakeFields: [
    {
      id: "tip",
      label: "The one tip you can teach at about 60 seconds and above",
      placeholder: "Concrete tip, not a vague theme",
      required: true,
      multiline: true,
    },
    {
      id: "whoHelps",
      label: "Who it helps",
      placeholder: "Audience this tip is for",
      required: true,
    },
    {
      id: "nextStep",
      label: "Gentle next step",
      placeholder: "Follow, save, DM keyword, or light booking invite",
      required: true,
    },
    {
      id: "language",
      label: "Language preference",
      placeholder: "English, Chinese, or mixed",
      required: true,
    },
  ],
  qualitySlots: [
    {
      id: "tip",
      label: "The one tip you can teach at about 60 seconds and above",
      criticality: "critical",
      probeHint: "One concrete tip they can teach openly, not a vague theme.",
      placeholder: "Concrete tip, not a vague theme",
      multiline: true,
      idkOptions: [
        "One daily habit that quietly fails, and the fix that sticks (scaffold; they correct).",
        "A common myth in their niche, then the clearer method (scaffold; they correct).",
        "A short how-to they already teach clients in person (scaffold; they correct).",
        "Or name the tip in one plain sentence of their own.",
      ],
    },
    {
      id: "whoHelps",
      label: "Who it helps",
      criticality: "critical",
      probeHint: "Who should feel spoken to when the tip lands?",
      placeholder: "Audience this tip is for",
      idkOptions: [
        "People new to their niche who feel overwhelmed (scaffold; they correct).",
        "People who already know basics but keep slipping (scaffold; they correct).",
        "Caregivers or partners supporting someone in the niche (scaffold; they correct).",
        "Or name who it helps in their own words.",
      ],
    },
    {
      id: "nextStep",
      label: "Gentle next step",
      criticality: "critical",
      probeHint: "Soft invite after value: follow, save, DM keyword, or light booking.",
      placeholder: "Follow, save, DM keyword, or light booking invite",
      idkOptions: [
        "Soft: follow or save for the next tip.",
        "Medium: DM a simple keyword for a checklist.",
        "Light invite: comment if this is their stuck point.",
        "Or name the gentle next step they already use.",
      ],
    },
    {
      id: "language",
      label: "Language preference",
      criticality: "critical",
      probeHint: "Match how they speak on camera: English, Chinese, or mixed.",
      placeholder: "English, Chinese, or mixed",
      idkOptions: [
        "English only, spoken and filmable.",
        "Chinese only, spoken and filmable.",
        "Mixed: Chinese spoken with short English terms they already use.",
      ],
    },
  ],
  idkOptionsBySlotId: {
    tip: [
      "One daily habit that quietly fails, and the fix that sticks (scaffold; they correct).",
      "A common myth in their niche, then the clearer method (scaffold; they correct).",
      "A short how-to they already teach clients in person (scaffold; they correct).",
      "Or name the tip in one plain sentence of their own.",
    ],
    whoHelps: [
      "People new to their niche who feel overwhelmed (scaffold; they correct).",
      "People who already know basics but keep slipping (scaffold; they correct).",
      "Caregivers or partners supporting someone in the niche (scaffold; they correct).",
      "Or name who it helps in their own words.",
    ],
    nextStep: [
      "Soft: follow or save for the next tip.",
      "Medium: DM a simple keyword for a checklist.",
      "Light invite: comment if this is their stuck point.",
      "Or name the gentle next step they already use.",
    ],
    language: [
      "English only, spoken and filmable.",
      "Chinese only, spoken and filmable.",
      "Mixed: Chinese spoken with short English terms they already use.",
    ],
  },
  probeHints: [
    "value then convert",
    "teach openly",
    "content asset",
    "not ads",
    "short video",
    "trust",
    "先给价值再转化",
    "内容资产",
    "不是广告",
    "短视频",
    "probe_jeff",
  ],
  boundNodeIds: [
    "cl.value-then-convert",
    "cl.content-not-ads",
    "pr.exposure-trust-conversion",
    "cl.short-vs-long-video",
  ],
  starterPrompt:
    "Using my intake, script a dense value-led Reel at about 60 seconds and above that teaches one tip openly, then adds a light next step. Keep convert soft.",
  chatOpener: buildLifecycleOpener({
    jobLine: "I'll help you script a value-led Reel at about 60 seconds and above: teach one tip openly, then a light next step.",
    firstAsk: "What is the one tip you can teach at about 60 seconds and above?",
    seed: "value-teaching-reel",
  }),
  chatOpenerZh: buildLifecycleOpenerZh({
    jobLine: "我来帮你写一条价值向 Reel，大约 60 秒及以上：先公开教一招，再给一个轻下一步。",
    firstAsk: "你能用大约 60 秒及以上教完的那一招是什么？",
    seed: "value-teaching-reel",
  }),
  systemOverlay: [
    "## Module mode: Value Teaching Reel (qualityRuntime Script/Spoken)",
    "You are running the Value Teaching Reel tool for this user.",
    "Job: produce a dense, shootable value-led Reel at about 60 seconds and above that teaches one tip openly, then a light next step.",
    "Lifecycle is hard: Collect → Confirm → Deliver → Refine. Do not dense-dump in Collect. Confirm before the first full script unless they explicitly say just write it after criticals are filled.",
    "",
    "### Distinct job (not OPENS / not process proof / not hot take)",
    "Value first; soft convert later. Tip full on camera. Close is invite after value, not a hard sell flip in second one.",
    "Reject thin tip teasers that withhold the teaching. Reject hard-sell Reels with a tip glued on.",
    "",
    "### Jeff pivots (must show in the work, not as a lecture)",
    "Lead with open valuable content (先给价值再转化). Content assets are not ads.",
    "If a draft sounds like a sales Reel with a tip glued on, invert: tip full, convert soft.",
    "",
    "### Critical slots (Collect gate)",
    "Need before Confirm: tip, who it helps, gentle next step, language.",
    "Ask at most 1 to 2 questions per Collect turn. Prefer Jeff-shaped asks (the tip, who it helps) over \"tell me about your business\".",
    "If they say I do not know / blank, offer pack IDK choices. Do not invent niche medical facts or private proof.",
    "User owns niche facts. Jeff owns craft (value-then-convert shape, soft Step).",
    "",
    "### Confirm (before first dense Deliver)",
    "Mirror the plan in 2 to 4 bullets. Name assumptions honestly. Ask for go-ahead.",
    "Do not write the full timed script in Confirm.",
    "",
    "### Deliverable shape (dense; ~60s+)",
    "1. Hook that promises the tip without hard pitch + approximate seconds.",
    "2. Teaching beat: speakable steps that fully give the tip + approximate seconds.",
    "3. Light invite aligned with their next step + approximate seconds.",
    "4. Optional on-screen text cues.",
    "5. End with named refine levers (tighter Hook, clearer teaching steps, softer next step).",
    "Timing should read as about 60 seconds and above, not a thin short cut.",
    "Ground every beat in their concrete answers. Different tips must produce different scripts.",
    "Write the whole script in the locked UI locale language.",
    "",
    "### Refine",
    "After a dense script exists, tweak named levers only. Do not re-interrogate filled critical slots.",
    "",
    "### Hard bans",
    "No overnight-fame promises. No inventing Jeff patient/clinic/workshop case studies as doctrine.",
    "Prefer cl.value-then-convert, cl.content-not-ads, pr.exposure-trust-conversion, cl.short-vs-long-video when present.",
    "Sources only from probe / probe_jeff. Thin coverage: Generally → Jeff → steer, still Jeff-aide voice.",
  ].join("\n"),
};
