import type { ModulePack } from "@/lib/modules/types";

/**
 * Value → Convert Ladder: map drop-off onto 客户购买路径 1 to 7
 * (`fw.customer-purchase-paths`). Not generic rungs-only soft-sell.
 */
export const VALUE_CONVERT_LADDER_PACK: ModulePack = {
  moduleId: "value-convert-ladder",
  intakeFields: [
    {
      id: "freeTeach",
      label: "What you teach for free",
      placeholder: "Tips, frameworks, stories you already share",
      required: true,
      multiline: true,
    },
    {
      id: "sell",
      label: "What you sell",
      placeholder: "Offer, service, product, or booking",
      required: true,
    },
    {
      id: "dropOff",
      label: "Where people drop off",
      placeholder: "Liked the tip but not ready to talk: where it breaks",
      required: true,
      multiline: true,
    },
    {
      id: "pathGuess",
      label: "Likely purchase path (1 to 7)",
      placeholder: "e.g. 路径1 内容→私讯→客户, or longer path needing follow-up",
      required: false,
    },
    {
      id: "audience",
      label: "Audience",
      placeholder: "Who this path is for",
      required: false,
    },
  ],
  probeHints: [
    "客户购买路径",
    "内容→私讯→客户",
    "内容→信任→到店",
    "内容→转介绍",
    "长决策路径",
    "先给价值再转化",
    "成交",
    "信任",
    "内容资产",
    "不是广告",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.customer-purchase-paths",
    "cl.value-then-convert",
    "cl.content-not-ads",
    "pr.exposure-trust-conversion",
    "tm.content-asset",
  ],
  starterPrompt:
    "Using my intake, name the Jeff 客户购买路径 (paths 1 to 7) that fits, map where people drop off on that path, and prescribe the next content moves. No generic rung ladder theater.",
  chatOpener:
    "I will name your 客户购买路径 (paths 1 to 7) and map where people drop off. What do you teach for free, and what do you sell?",
  chatOpenerZh:
    "我会点名你的客户购买路径（路径1 to 7），并标出掉点。你免费教什么，卖的是什么？",
  systemOverlay: [
    "## Module mode: Value → Convert Ladder (客户购买路径)",
    "You are running the Value → Convert Ladder tool for this user.",
    "Exact Jeff framework: Customer purchase paths 1 to 7 / 客户购买路径 (`fw.customer-purchase-paths`).",
    "Job: name the path, map drop-off, and prescribe content moves so convert does not appear out of nowhere.",
    "",
    "### Path vocabulary (hard; use Jeff terms)",
    "1. 路径1 内容→私讯→客户",
    "2. 路径2 内容→信任→到店/询问",
    "3. 路径3 内容→转介绍",
    "4. 路径4 to 7 长决策路径 + 跟进系统 (name as long-decision when their cycle needs follow-up systems)",
    "Short paths are 1 to 3. Long paths 4 to 7 need follow-up systems; say so when true.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks over a generic business questionnaire.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "Do NOT deliver a generic \"rungs only\" soft-sell ladder.",
    "1. Named path: pick 路径1 / 路径2 / 路径3 / or 路径4 to 7 (long decision) and say why in one sentence.",
    "2. Drop-off map: pin their stated gap onto a stage of that path (content → next step).",
    "3. Content moves: 2 to 4 concrete assets that repair that gap (still value-then-convert; coach-like language).",
    "4. Next invite: one honest next conversation matched to the path (私讯 / 到店询问 / 转介绍 ask / follow-up system step).",
    "5. Reminder: convert after value; content assets are not ads.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume; value then convert where relevant.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Bind to `fw.customer-purchase-paths`. Lead with open valuable content; convert after trust/value.",
    "No overnight-fame promises. Never invent Jeff niche case studies or full offer architecture as confirmed doctrine.",
    "Do not invent Epic Pitch / funnel brand names. Stay on purchase-path language.",
    "",
    "### Evidence binding",
    "Prefer: fw.customer-purchase-paths, cl.value-then-convert, cl.content-not-ads, pr.exposure-trust-conversion, tm.content-asset when in the evidence pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the path map",
    "End with one direct question that locks which path stage they will film next.",
  ].join("\n"),
};
