import type { ModulePack } from "@/lib/modules/types";

/**
 * 定位一句话：三行地图 (D1 p038).
 * Module id kept as who-i-serve for stable routes.
 */
export const WHO_I_SERVE_PACK: ModulePack = {
  moduleId: "who-i-serve",
  intakeFields: [
    {
      id: "whoAmI",
      label: "我是谁",
      placeholder: "Identity, industry, experience, role (concrete, not vague)",
      required: true,
      multiline: true,
    },
    {
      id: "whoIHelp",
      label: "我帮谁",
      placeholder: "Who you serve: role, situation, or life stage (not everyone)",
      required: true,
    },
    {
      id: "whatISolve",
      label: "解决什么",
      placeholder: "The problem or change the market buys (not only your bio)",
      required: true,
      multiline: true,
    },
    {
      id: "proofOfFit",
      label: "One proof of fit (optional)",
      placeholder: "Result, story, or pattern you can show without inventing cases",
      required: false,
      multiline: true,
    },
  ],
  probeHints: [
    "定位一句话",
    "三行地图",
    "我是谁",
    "我帮谁",
    "解决什么",
    "buy people not product",
    "ideal customer",
    "standpoint",
    "personal IP",
    "买人",
    "谁是客户",
    "立场",
    "probe_jeff",
  ],
  boundNodeIds: [
    "fw.positioning-three-line-map",
    "cl.buy-people-not-product",
    "pr.standpoint-or-invisible",
    "pr.founder-face-printshop",
    "pr.exposure-trust-conversion",
  ],
  starterPrompt:
    "Using my intake, write the full 定位一句话：三行地图 (我是谁 / 我帮谁 / 解决什么), plus one content angle that shows people-first fit.",
  chatOpener:
    "I will build Jeff's 定位一句话：三行地图: 我是谁, 我帮谁, 解决什么. Start with 我是谁: identity, industry, experience, role in plain words.",
  systemOverlay: [
    "## Module mode: 定位一句话：三行地图",
    "You are running the 定位一句话：三行地图 tool (catalog id who-i-serve) for this user.",
    "Exact Jeff slide title (AUG-D1 p038). Job: fill all three lines so the market quickly understands who they help.",
    "Slide lines: 我是谁 / 我帮谁 / 解决什么.",
    "Slide framing: 定位不是介绍自己，而是让市场最快理解你能帮谁.",
    "Do not invent a different Jeff brand name.",
    "",
    "### Conversational collect (chat-first; no form)",
    "Slots live in conversation history. Ask at most 1 to 2 questions per turn.",
    "Prefer Jeff-shaped asks over a generic business questionnaire.",
    "Collect 我是谁, 我帮谁, 解决什么. Optional proof of fit.",
    "When enough is known, or the user says just write it, deliver the full output and name assumptions.",
    "",
    "### Output format (when ready to generate)",
    "1. 我是谁: identity, industry, experience, role (concrete).",
    "2. 我帮谁: who they serve; clear enough that content will not scatter.",
    "3. 解决什么: what the market buys (problem solved / change), not only who they are.",
    "4. One optional one-liner that stitches the three lines for profile or camera.",
    "5. One content angle that shows fit without hard sell.",
    "6. Reject note: do not center cheapest/loudest product framing.",
    "",
    "### Jeff distinctiveness (hard)",
    "Use Jeff mechanisms in the user's language: get seen before trust before deal; standpoint; content assets not ads; advice vs ego; direction beats volume; value then convert where relevant.",
    "ANTI-GENERIC: If this reply could have come from a generic LinkedIn coach with no Jeff graph, rewrite before sending.",
    "",
    "### Doctrine rules (hard)",
    "Bind to fw.positioning-three-line-map and buy-people-not-product when evidence hits. No overnight-fame. Never invent Jeff niche case studies as doctrine.",
    "Niche facts come from the conversation.",
    "",
    "### Evidence binding",
    "Prefer: fw.positioning-three-line-map, cl.buy-people-not-product, pr.standpoint-or-invisible, pr.founder-face-printshop, pr.exposure-trust-conversion when in the pack.",
    "Sources still come only from probe / probe_jeff.",
    "",
    "### After the map",
    "End with one direct question that tightens which line they will film first.",
  ].join("\n"),
};
